### ISSUE TITLE
'.local' mDNS addresses aren't handled as needed

### ISSUE THREAD

**Issue by fushinari** [jarnedemeulemeester/findroid#109]
**Describe the bug**
The system DNS resolver in Android does not resolve mDNS addresses like 'my-server.local' ([bug report](https://issuetracker.google.com/issues/140786115)). In Android, the NSD API needs to be used by the application's developer in order to implement support for such servers.

**To Reproduce**
1. Setup Jellyfin on a system with hostname `my-server` and use Avahi to publish the server on LAN.
2. Enter `http://my-sever.local:8096` in address field of Findroid.
3. Won't work.

**Expected behavior**
Like on any other OS, we expect it to just find the server. This helps a lot with cases where the user has no control over their IP addresses for example.

**Device info (please complete the following information):**
 - Device: Mi A3
 - Android version: 12.1
 - App version: 0.4.0

**Additional context**
This is really Android's fault. Every other major platform has support for mDNS resolution. But would be cool if Findroid could fix a shortcoming of the OS.

**Comment by jarnedemeulemeester** [comment]
Hi

This is indeed something that would be useful for a lot of people.

mDNS should be working as of Android 12 and Google Play System Update November 2021.
https://source.android.com/devices/architecture/modular-system/dns-resolver#mdns-local-resolution
https://issuetracker.google.com/issues/140786115#comment316

I have not tested this myself, but will do so later today.

I see you are running Android 12.1, are you running a custom ROM?

**Comment by jarnedemeulemeester** [comment]
I used `<hostname>.local` as the server address and was able to connect.
Everything else also seems to work.

I will not be implementing the NSD API in my app because this has been fixed by Android itself.
