### ISSUE TITLE
Missing Thumbnails 

### ISSUE THREAD

**Issue by chmol** [jarnedemeulemeester/findroid#11]
I've just installed the app and logged in my server. Everything is smooth as butter but there are no thumbnails. I restarted the app and waited 5-10 minutes with no changes. 

Android: 7.1.2 (LineageOs 14)
device: Moto G

ps: it's awesome to be able to enjoy jellyfin on an older device, the native app is really slughish.

**Comment by jarnedemeulemeester** [comment]
Weird that there are no thumbnails.
Any way to test the app on an other device?

Ps thanks for enjoying it!

**Comment by Parlendir** [comment]
Hello.
I have the same problem: the previews are not displayed but everything else is perfectly functional.
My local jellyfin server is configured not to save the metadatas/posters... in the media file directories. I don't know if this has anything to do with it.
Please let me know if and how I can help.

**Comment by Mylloon** [comment]
I have similar issue with a Xiaomi Mi Note 10 Lite, there is no thumbnails but beyond that it's rock solid

**Comment by Parlendir** [comment]
@Mylloon did you change anything on the server side ? or on the android side ? My thumbnails are always missing

**Comment by Mylloon** [comment]
@Parlendir I change nothing neither at the server nor at the client side

I use the Docker image of linuxserver in version 10.7.7

**Comment by Parlendir** [comment]
@Mylloon Thanks for your answer. I've just checked and am on the v10.7.2 of jellyfin server.
I'll wait for the v10.8.1 to be out to try the update.

**Comment by Parlendir** [comment]
Upgrading server from 10.7.2 to 10.7.7 solved this issue for me.

**Comment by jarnedemeulemeester** [comment]
@chmol are you still having issues with missing thumbnails?
I will close this issue as upgrading the server to 10.7.7 seems to fix it.

If you are still having problems feel free to reopen.

**Comment by DUOLabs333** [comment]
I still have this issue testing this app on demo.jellyfin.org/stable (which crashes if you don't add a slash at the end of the url, but that's a different issue)

**Comment by jarnedemeulemeester** [comment]
@DUOLabs333 I just tested the latest release (0.4.0) with the demo server "demo.jellyfin.org/stable" and it works without any issues.
It immediately connects without any crashes or problems and all images are working
