### ISSUE TITLE
Images in library not loading at all

### ISSUE THREAD

**Issue by AtlasC0R3** [jarnedemeulemeester/findroid#113]
**Describe the bug**
So, for some reason, if I am on my Pixel 6, no images load. Everything else works perfectly; metadata and video streaming *(and subtitles but #7)*. Just not the images.
What's weird is that my Galaxy S6 Edge with a custom ROM and even microG and AdAway installed, everything works flawlessly. Images load no problem. So I guess it's an issue with the way the Pixel ROM does things specifically? I don't know.

I have tried playing around with the image caching option, to no avail.

**To Reproduce**
1. Open Findroid
2. Go on whatever page that has images (home screen, media display or libraries)

**Expected behavior**
Well, I'd be expecting actual images be there instead of gray placeholders.

**Screenshots**
![Screenshot_20220423-205138](https://user-images.githubusercontent.com/39468657/164951192-6c022cea-c696-4383-a996-76ec35c68a6b.jpg)
Above is how it looks like on my Galaxy S6 Edge

![Screenshot_20220423-205140](https://user-images.githubusercontent.com/39468657/164951200-464882da-932d-4398-b42d-a4edac20bac6.png)
Above is on my Pixel 6. Exact same page.

**Device info (please complete the following information):**
Device of first screenshot (that works):
 - Device: Samsung Galaxy S6 Edge (custom ROM with crDroid 6.5)
 - Android version: 10
 - App version: 0.3.2 Play Store (installed via Aurora and microG)
**Device of second screenshot (the one that can't load images):**
 - Device: Google Pixel 6
 - Android version: 12
 - App version: 0.3.2 Play Store (installed from the actual Play Store)

**Additional context**
I really like the way this client looks, too. Keep up the good work! I love this client, and the ability of downloading movies/shows.

**Comment by AtlasC0R3** [comment]
Found the issue, and it's a rather strange fix:
I put a slash (`/`) at the end of the address. That was what was causing it to freak out.
So now I have it set up like `http://123.456.789.012:3456` instead of `http://123.456.789.012:3456/`. Having a slash at the end of the address will cause issues.

**Comment by jarnedemeulemeester** [comment]
I am reopening this because this is still a problem that needs to be fixed.
A user should be able to enter an address with or without a slash `/` at the end and have all images load.
Thanks for bringing this to my attention.
