### ISSUE TITLE
Findroid is unable to obtain any data from the server

### ISSUE THREAD

**Issue by gandbg** [jarnedemeulemeester/findroid#131]
**Describe the bug**
When Findroid tries to obtain some data from the server it return a `java.lang.NullPointExeption` error

**To Reproduce**
1. Go to any tab in the main page
2. See the error

**Expected behavior**
Findroid fetches the informations that is need to correctly display the various movies/shows

**Screenshots**
![photo_2022-07-17_01-58-26](https://user-images.githubusercontent.com/62039938/179375511-3fb2232d-6847-4149-8291-aa715cbe6d8f.jpg)
![photo_2022-07-17_01-58-27](https://user-images.githubusercontent.com/62039938/179375520-94f956c1-cf48-42c1-bcd1-30a2e63c0bf4.jpg)

**Device info:**
 - Device: Xiaomi Redmi Note 7
 - Android version: 11
 - App version: v0.5.0

**Comment by rdmchr** [comment]
Same problem, exact same error:
Device: OnePlus Nord
Android Version: 12
App Version: 0.5.0

**Comment by jarnedemeulemeester** [comment]
What version of the Jellyfin server are you running?
The latest update ups the minimum version to 10.8.1.

You can also try resetting the app data and adding the server again.

**Comment by Hjaelp** [comment]
@jarnedemeulemeester I'm not sure if what I had is the same since it didn't completely crash for me, but I was getting the same error although with 401 HTTP response as well when I inspected it. I had to re-add the server for it to work.

**Comment by rdmchr** [comment]
> As a temporary workaround if you manage to get to the home screen (maybe after multiple crashes) and get the `NullPointerExeption` try going to Settings -> Manage servers -> Select your server.

This did actually work for me. Thank you!

**Comment by jarnedemeulemeester** [comment]
@gandbg could you test again on version 0.6.0?
I suggest clearing all app data before you try again. (Just to make sure)

**Comment by rdmchr** [comment]
Not gandbg, but the update did resolve the issue for me. 👍

**Comment by gandbg** [comment]
> @gandbg could you test again on version 0.6.0? I suggest clearing all app data before you try again. (Just to make sure)

I've updated the app, deleted all app data and it was able to fetch everything that it needed.
