### ISSUE TITLE
Support movie logos

### ISSUE THREAD

**Issue by michaelharmonart** [jarnedemeulemeester/findroid#14]
One of my favorite bits of the normal jellyfin app is that you can skin it with css, including changing out the title on the movie page for it's logo image. I think this would be a great option to add to findroid.

**Comment by jarnedemeulemeester** [comment]
Yes I do agree that this would be nice to have.
My priority for now is stability and usability, make sure that everything that the app offers works well.

But this could be a nice feature in the future!

**Comment by jarnedemeulemeester** [comment]
After some thinking about it. We will stick with the text titles instead of the logos
