### ISSUE TITLE
[Feature request] support for Intro skipper and Jellyscrub plugins

### ISSUE THREAD

**Issue by JVT038** [jarnedemeulemeester/findroid#146]
Hi,
It may be too early to make this feature request, but I recently installed [Intro-skipper](https://github.com/ConfusedPolarBear/intro-skipper), which scans all episodes and detects the intro, and then shows a button to the user to skip the intro, and I would like to have this on findroid as well.

Another plugin I would like to have support for, is [Jellyscrub](https://github.com/nicknsy/jellyscrub) which generates scrubbing images, so when the user hovers the mouse or slides the playback position, it shows little miniatures of 320x180px. Kind of like YouTube shows the little miniatures.

**Comment by StopmotionSimonYT** [comment]
Hi, 
Thanks for the suggestion. But I think it is not possible, because findroid plays just the video file. @jarnedemeulemeester correct me if I am wrong please.

Btw: thanks for the suggestion of jellyscrub.

**Comment by JVT038** [comment]
For the intro skipper, wouldn't it be possible to use the [API endpoints](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/api.md), fetch any available timestamp for a certain episode and then show a skip button?

**Comment by StopmotionSimonYT** [comment]
> For the intro skipper, wouldn't it be possible to use the [API endpoints](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/api.md), fetch any available timestamp for a certain episode and then show a skip button?

I didn't know that the intro skipper has an API. Then it is possible.

**Comment by JVT038** [comment]
1. Also, Jellyscrub appears to have somes sort of API for requesting previews / thumbnails, thats sort of documented [here](https://github.com/nicknsy/jellyscrub/blob/main/Nick.Plugin.Jellyscrub/Api/TrickplayController.cs).

Its usage can be seen in action [here](https://github.com/nicknsy/jellyscrub/blob/main/Nick.Plugin.Jellyscrub/Api/trickplay.js)

**Comment by jarnedemeulemeester** [comment]
The intro skipper is something I probably will be able to implement. But I won't give this high priority because it's not an official Jellyfin feature.

Jellyscrub would be a lot more difficult because of the UI and code changes required.

**Comment by jarnedemeulemeester** [comment]
Intro Skipper has been implemented!

I do not plan on implementing Jellyscrub anytime in the foreseeable future so I will close this issue.
