### ISSUE TITLE
Star Rating is shifted

### ISSUE THREAD

**Issue by kjboa** [jarnedemeulemeester/findroid#15]
Hi, so far i really like your app. I found a really minor issue though.
The Star Rating in the Episodes view is shifted and looks weird:
![Screenshot_2021-08-22-12-02-15-25_aff99014c254344a005aaf8c1683039d.jpg](https://user-images.githubusercontent.com/65646265/130351492-47093bf8-e902-49d0-b994-811a41e68d71.jpg)

Looking forward to more great releases 👍

**Comment by jarnedemeulemeester** [comment]
Thanks a lot!

I moved the metadata to underneath the image. 
It is not the best solution, but it will work for now :)
