### ISSUE TITLE
[Feature Request] Picture in picture

### ISSUE THREAD

**Issue by rdmchr** [jarnedemeulemeester/findroid#152]
It would be great if the app allowed picture in picture mode.
This could allow you to for example continue watching a show or movie in background while responding to text messages.

**Comment by AndreSchwarzer** [comment]
There is pr #237 covering this request

**Comment by cd16b** [comment]
#277

**Comment by Yash-Garg** [comment]
> There is pr #237 covering this request

That PR is closed for some reason, there is https://github.com/jarnedemeulemeester/findroid/pull/277 that implements it.

@rdmchr
