### ISSUE TITLE
Support for Mixed Content Libraries (Movies and series)

### ISSUE THREAD

**Issue by JulioNahum** [jarnedemeulemeester/findroid#154]
**Describe the bug**
Right now when adding a library with mixed content, the chapters of the series are combined with the movies and vice versa.

**Screenshots**

https://user-images.githubusercontent.com/30002132/187086610-cfa76838-acfc-4439-a03a-35d43af14588.mp4

**Device info (please complete the following information):**
 - Device: [MOTOROLA EDGE 20 PRO]
 - Android version: [ANDROID 12]
 - App version: [v0.6.0]

**Additional context**
Someday there will be that support?****

**Comment by AnonymousWebHacker** [comment]
Me parece un problema del servidor jellyfin, no de Findroid app. Comprueba si el contenido esta mixeado asi usando jellyfin cliente
