### ISSUE TITLE
[Feature Request] Video Chapter Features

### ISSUE THREAD

**Issue by CodeName393** [jarnedemeulemeester/findroid#158]
If there's chapter information in the video, I'd like to be able to move the chapter.
also, If the name of the chapter is OP, Opening, 여는곡, 오프닝, オープニング, 開く曲 etc., I would like to have an opening skip button.

**Comment by Natanel-Shitrit** [comment]
You are welcome to see my PR (#466)
Added chapter markers and an option to skip chapters with a gesture!
Still WIP but should finish it soon :D

**Comment by jothi-prasath** [comment]
+1
