### ISSUE TITLE
App stuck on initial loading screen (Android TV) 

### ISSUE THREAD

**Issue by krutburken** [jarnedemeulemeester/findroid#159]
**Describe the bug**
App won't start and hangs on the spinning loading screen during first startup. Works fine on my phone so I guess it's related to Android TV.

**To Reproduce**
1. Install app on Android TV device. Start app
2. App gets stuck on initial loading screen and won't go any further

**Expected behavior**
App starting successfully

**Device info (please complete the following information):**
 - Device: Nvidia Shield TV
 - Android version: 11
 - App version: v0.6.1

**Comment by jarnedemeulemeester** [comment]
Have you tried clearing the app storage?
Sometimes that fixes certain problems.

**Comment by neopc10** [comment]
Plug a mouse in via USB and click the gear on the top right. I don't know if theres login screen code for ATV.

**Comment by krutburken** [comment]
Hi, yes I tried clearing the storage several times but the issue persists.

Sadly the Shield TV has no usb-ports so can't really try that. Don't have any bluetooth equipment either

**Comment by deepika05** [comment]
a quick workaround for this as of 0.6.1 would be to roll back to 0.5, add a server (no need to set anything else up) and then update to 0.6.1

**Comment by jarnedemeulemeester** [comment]
I was able to reproduce this. 
Will look into fixing it now.
