### ISSUE TITLE
libVLC support

### ISSUE THREAD

**Issue by viggy96** [jarnedemeulemeester/findroid#16]
libVLC could be an option for SSA/ASS support while we wait (forever) for ExoPlayer to finally implement proper support for it. The Jellyfin Android TV app uses it and it works pretty well. It crashes occasionally, but overall its pretty good.

**Comment by jarnedemeulemeester** [comment]
Yes, libVLC would probably be the best way to support SSA/ASS subs for now. And is probably easier to implement than libmpv. 

I think I will add it as an option in the settings to switch to VLC.
I will try to implement this sometime in the future.

**Comment by viggy96** [comment]
MPV could also be worth a look. Someone else made a pull request to jellyfin-android with mpv support.

https://github.com/jellyfin/jellyfin-android/pull/475

**Comment by jarnedemeulemeester** [comment]
I have implemented the mpv player from jellyfin/jellyfin-android#475 as an experimental option.

I will close this but feel free to open new issues if there are problems with the mpv player.
