### ISSUE TITLE
[Feature Request] Option to add 2nd adress for access outside local network

### ISSUE THREAD

**Issue by carrierfry** [jarnedemeulemeester/findroid#164]
It would be great to be able to add a secondary address to a server. That way you can have the local IP adress as the primary way to connect, but if you are not connected to the same network as the Jellyfin server you can access it via it's public IP.

Alternatively it would also be fine to add the same server a second time via it's public IP, but that's not possible right now unfortunately.

**Comment by Just5KY** [comment]
+1 on this
I would like a to access server locally when I'm at home.

**Comment by CodeName393** [comment]
+1
I think this feature is necessary, too.

**Comment by Ge082** [comment]
Isn't a reverse proxy what you're searching for ?

**Comment by jarnedemeulemeester** [comment]
This has been implemented in #208 

Currently you have manually tap the server address in the settings to switch to it.

**Comment by kid1412621** [comment]
how about allowing use to config a specific address based on SSID? 
like when connected to home wifi, the address to use is jellyfin.internal.local
otherwise, use jellyfin.external.com
