### ISSUE TITLE
Getting a lot of Socket timeout errors

### ISSUE THREAD

**Issue by guss77** [jarnedemeulemeester/findroid#175]
**Describe the bug**
My Jellyfin server is a bit slow and underpowered, and when using Findroid I get a lot of `SocketTimeout` errors.

It would be nice to be able to set a different timeout as 10 seconds is a bit low for my system.

**Device info (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 13
 - App version: 0.6.1

**Comment by jarnedemeulemeester** [comment]
I will look into adding the option to set a custom socket timeout

**Comment by guss77** [comment]
Thank you! ✌️😎
