### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by TobiFlobi26** [jarnedemeulemeester/findroid#18]
No content, such as movies or shows, is displayed in collections, they are just empty.

Android: 11 (OneUi 3.1)

**Comment by jarnedemeulemeester** [comment]
Hi, sorry for the late response.

Do you mean that all the libraries are empty?
Could you provide a screenshot or a video?

**Comment by TobiFlobi26** [comment]
I have enabled the _Libraries > Display > Group movies into collections_ setting in Jellyfin to display the movies in my movie list as one grouped item.
In Findroid, these groups are empty and I can't play the movies.

![screenshot_jellyfin_collection_web](https://user-images.githubusercontent.com/65586860/131224528-468bcaef-2e46-482e-b1d9-45d8dfade7ec.png)
![screenshot_jellyfin_collection_findroid](https://user-images.githubusercontent.com/65586860/131224560-fc06860f-6244-4dc9-837b-76dd49dee4dd.jpg)
