### ISSUE TITLE
Bug: App freezes temporarily after quitting the player

### ISSUE THREAD

**Issue by JVT038** [jarnedemeulemeester/findroid#181]
**Describe the bug**
When I'm playing something and I quit the player, the app will temporarily freeze and be unresponsive for a couple of seconds. This is annoying

**To Reproduce**
1. Play an item
2. Quit the player
3. See error

**Expected behavior**
I expected the app to smoothly refresh the next up / continue watching overview, without freezing..

**Device info (please complete the following information):**
 - Device: Fairphone 4
 - Android version: 11
 - App version: 0.6.1

**Additional context**.
This happens to all items, regardless of their resolution, video codec or other individual properties. 
It occurs with and without MPV player enabled

**Comment by jarnedemeulemeester** [comment]
This has been fixed for quite some time in a more recent version. :smile:
