### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by ohitstom** [jarnedemeulemeester/findroid#188]
When you say "Direct play only, (no transcoding)"

Does that rule out all lower resolution picking and certain media containers that the device and/or mpv doesn't natively support?

I doubt this is a lot of media as mpv covers a vast majority, but is adding support for transcoding ever coming in the near future?

Also are there any thoughts on adding more native jellyfin settings such as many administrator specific ones like library management or dashboard?

What about subtitle preferences that don't rely on system settings? I find the subtitles with mpv to be much smaller than when using the external mpv app for some reason.

Lastly, would an option to try and match the servers served css be in the question whatsoever? I assume as it's not entirely a webwrapper like jellyfin-android that this is an impossibility but maybe your own alternative would be great..

**Comment by jarnedemeulemeester** [comment]
> When you say "Direct play only, (no transcoding)"
>
> Does that rule out all lower resolution picking and certain media containers that the device and/or mpv doesn't natively support?

Yes. There is currently no resolution picker or transcoding happening on the server side. It just requests the exact file you have stored on your server.

> I doubt this is a lot of media as mpv covers a vast majority, but is adding support for transcoding ever coming in the near future?

I can't say it will happen in the "near" future. But it is something I want to add yes.

> Also are there any thoughts on adding more native jellyfin settings such as many administrator specific ones like library management or dashboard?

Yes! I have been thinking about that for a while now. It's something I want to work on in the future but for now the focus is more on consuming content.

> What about subtitle preferences that don't rely on system settings? I find the subtitles with mpv to be much smaller than when using the external mpv app for some reason.

The subtitles preferences for the default player (ExoPlayer) will stay in the system settings. For editing the subtitles (and other settings) for mpv I will add a section in the app. At first this will be just a text field for editing the `mpv.conf` file. As a workaround for now you can already edit the `mpv.conf` file using a file browser app on your device or via a computer. The file is located in `Android/data/dev.jdtech.jellyfin/files/mpv/`. Why the subtitles are smaller with mpv in Findroid than the official mpv app I cannot tell you. 

> Lastly, would an option to try and match the servers served css be in the question whatsoever? I assume as it's not entirely a webwrapper like jellyfin-android that this is an impossibility but maybe your own alternative would be great..

Currently I have no plans to add such a feature.

**Comment by ohitstom** [comment]
Awesome thank you
