### ISSUE TITLE
License dialog

### ISSUE THREAD

**Issue by IzzySoft** [jarnedemeulemeester/findroid#2]
Unfortunately, the Google Play OSS-Licenses library (`com.google.android.gms.oss.licenses` – always be wary if something starts with `com.google.android.gms.`) you use drags in non-free dependencies (it's well known for that) – here, Google Mobile Services (GMS). Maybe you'd consider replacing that with a true FOSS [license dialog library](https://gitlab.com/-/snippets/1896503#license-dialogs)? The four examples listed behind the link use either Apache-2.0 or MIT licenses, and thus should be compatible with your chosen GPL-3.0 (at least if you're talking "or later" – I'm not a license specialist, so I cannot say for absolutely sure).

<details><summary>Library Scanner results</summary><pre>
Libraries detected:
-------------------
* Android Support v4 (/android/support/v4): Development Framework
* AndroidX Activity (/androidx/activity): Utility
* Android Jetpack Annotations (/androidx/annotation): Utility
* AppCompat (/androidx/appcompat): Utility
* Constraint Layout Library (/androidx/constraintlayout): Utility
* Androidx Core (/androidx/core): Utility
* Lifecycle (/androidx/lifecycle): Utility
* Media (/androidx/media): Utility
* Navigation (/androidx/navigation): Utility
* Preference (/androidx/preference): Utility
* Room (/androidx/room): Utility
* Android Activity Saved State (/androidx/savedstate): Utility
* Android Jetpack VersionedParcelable (/androidx/versionedparcelable): Utility
* AndroidX Widget ViewPager2 (/androidx/viewpager2): UI Component
* Glide (/com/bumptech/glide): Utility
* ExoPlayer (/com/google/android/exoplayer2): Utility
* Google Play OSS-Licenses (/com/google/android/gms/oss/licenses): UI Component
* Google Mobile Services (/com/google/android/gms): Development Framework NonFreeDep
* Google Material Design (/com/google/android/material): Utility
* OkHttp (/com/squareup/okhttp): Utility
* Dagger (/dagger): Utility
* Ktor (/io/ktor): Development Framework
* kotlinx.coroutines (/kotlinx/coroutines): Utility</pre>

<pre>Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep

1 offenders.
</pre></details>

By the screenshots, the app looks great! Looks like it's really time I give JellyFin a try…

**Comment by jarnedemeulemeester** [comment]
Oh I didn't know that, thanks! 
I will replace that library with one of the four examples you listed.

I want to implement Chromecast support later down the road. And that also requires GMS. 
Maybe when I do implement that, I can make two versions. One with non-free deps and one without, for the Google Play Store and F-Droid respectively. 
Because I do think that a lot of people would also like casting support.

**Comment by IzzySoft** [comment]
> I will replace that library with one of the four examples you listed.

Great! Then it will qualify for F-Droid.

> I want to implement Chromecast support later

Ugh. Hard decision: features versus FOSS. If you really want to do that (again tainting your nice FOSS apps with proprietary things), consider to use a separate build flavor at least – so there can still be a FOSS build by e.g. F-Droid.

> Maybe when I do implement that, I can make two versions. One with non-free deps and one without, for the Google Play Store and F-Droid respectively.

Exactly. I just wonder if "casting support" automatically means "Chromecast" – or whether there are other means. Jellyfin also supports DLNA, so why not integrating a "DLNA control point"/server instead? A server would show up on other devices, a control point can be used to tell a client what to play (basically, it could act as a mediator, like telling your TV to play that specific movie from your Jellyfin instance). AFAIK "Casting" you'd only need if you wanted to share your screen contents e.g. to a TV. As most multimedia devices support DLNA (to my knowledge, even more than support Chromecast/Miracast), DLNA would be the better way to go. And remain FOSS :wink:

**Comment by dkanada** [comment]
We have a native casting feature as well! Any client can implement Jellyfin's flavor of casting for remote control support in *both* directions. I always thought it was a hugely undervalued feature, even though it's a bit unpolished right now on the web clients.

**Comment by IzzySoft** [comment]
Thanks for chiming in, @dkanada! – @jarnedemeulemeester maybe that's the way to go then, for a proper Jellyfin client, wouldn't you agree? :smiley:

**Comment by jarnedemeulemeester** [comment]
Oh yeah I totally forgot about that. That's probably the way to go. I'll add it to the list of stuff I need to investigate.

Feel free to open a new issue for Jellyfin's casting support, let's keep this issue about the license dialog.
I should definitely setup a feature requests platform instead of relying on GitHub issues for features 😄

**Comment by IzzySoft** [comment]
Cool – thanks a lot! Looking forward to the next release, where I can drop the `NonFreeDep`.

Oh: maybe you want to complement that Google Play badge by [this one](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it), pointing to [your app here](https://apt.izzysoft.de/fdroid/index/apk/dev.jdtech.jellyfin), @jarnedemeulemeester?

**Comment by jarnedemeulemeester** [comment]
@IzzySoft done!

**Comment by IzzySoft** [comment]
:heart_eyes: That badge looks really nice there :smile: And the listing much better without that AntiFeature banner (with the next sync tomorrow – sorry for the delay, I was quite busy with my dayjob today). Thanks a lot!

**Comment by jarnedemeulemeester** [comment]
@IzzySoft I have released a new version with per-ABI builds. The size is around 30MB.
I will make an effort to reduce the size in the next update.

**Comment by IzzySoft** [comment]
Thanks! Nice XMas present :smile: Updated the YAML here (wish you had told me in advance, the updater meanwhile hat picked the x86 APK – had to replace it by the ARM one manually. With x86 being not that present on devices, not too many users should have been affected, though). Updater will now grab the armeabi variant.

And yes, please keep me updated. Should you manage to reduce the size to below 20M (unlikely, but who knows) I could allow to keep 2 versions.

Besides: are you interested in having [Fastlane structures](https://gitlab.com/snippets/1895688) established? I could send you an initial setup as PR. Multiple advantages with that:

* you can maintain yourself how your app is presented to the user
* updates would be pulled along with releases, so they would stay in sync
* you could even provide per-release changelogs shown along with the app description (optional of course)

Just let me know if you'd like that PR.

**Comment by jarnedemeulemeester** [comment]
Hi @IzzySoft 
The next release will be a bit bigger than 30MB. This is because I now include all codecs in the mpv (FFmpeg) library included in the app. 
Don't worry if you can't publish the app in your repo, I am working towards releasing in on F-Droid. 

The main issue I'm am still stuck with is the included binary .aar libraries, F-Droid doesn't allow those. I already migrated one of the two included libraries to their own repo and uploaded it to Maven central. But I am having trouble building the second library for inclusion in Maven central. So the next version (v0.9.0) won't be available on F-Droid yet.

PS I will also be looking at Fastlane when I do get that binary library out of this repo.

**Comment by IzzySoft** [comment]
Thanks for the warning, @jarnedemeulemeester – I'll won't reject that update right away then (30 M is no hard limit; there's some 32 M limit with one of the APIs I use, but if needed I can work around that – though I prefer to keep the number of apps I need to do that as low as possible).

Great you're working on F-Droid inclusion. Best luck for that last remaining AAR! Need to look which one it is; if [ffmpeg-android-maker](https://github.com/Javernaut/ffmpeg-android-maker) would work, I'd know how it could be included at F-Droid (there's a `srclib` set up for that which builds the dependency in preparation for the app build, can be configured with the `*.yml` of the app).
