### ISSUE TITLE
[Suggestion] Search button in main UI and live searches.

### ISSUE THREAD

**Issue by fmchris10** [jarnedemeulemeester/findroid#214]
A search button in the main UI would be a nice touch, instead of needing to go into the media tab.

Also, can the searches instantly respond to what is written? Showing the nearest results below.

**Comment by BluePixel4k** [comment]
Duplicate of #84 and #95

**Comment by jarnedemeulemeester** [comment]
Search button has been added to the home screen
This is a duplicate of #84 

The live searches / suggestions is a duplicate of #95. Let's discuss it there
