### ISSUE TITLE
Home page does not display

### ISSUE THREAD

**Issue by CakesTwix** [jarnedemeulemeester/findroid#223]
**Describe the bug**
An error is displayed at home. 

**To Reproduce**
1. Just open app
2. See error

**Expected behavior**
Displaying media you haven't finished watching, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/57946485/208391742-b91922c3-1549-42cc-b2c8-503801695959.png)
![image](https://user-images.githubusercontent.com/57946485/208391761-30be4cea-ce5d-43d3-807f-ae93deb800c3.png)
![image](https://user-images.githubusercontent.com/57946485/208391778-7a192939-c7df-4c3f-921a-9f205f5c978f.png)

**Device info (please complete the following information):**
 - Device: Lenovo Z5s
 - Android version: 13
 - App version: v0.8.0 (14)
 - Jellyfin version: 10.8.8, Linux Server, Arch based

**Comment by jarnedemeulemeester** [comment]
@CakesTwix  sorry for the late reply.

Could you add the complete (text) error to the bug report? The visible part of the error doesn't tell me enough.
You use the Share button to directly copy it and then paste it in the bug report.

Thanks!

**Comment by jarnedemeulemeester** [comment]
If this is no longer an issue than I will close this. I suspect this may have been an issue specific to Jellyfin from the AUR.
