### ISSUE TITLE
Login screen's back button doesn't do anything once server has been chosen

### ISSUE THREAD

**Issue by davemsh** [jarnedemeulemeester/findroid#235]
**Describe the bug**
On first start of Findroid, you get to choose a server, and then you move onto the login screen. However, if you don't actually log in, and close Findroid (swiping out of the app switch screen) the back button on the login screen doesn't do anything. To re-select a server, the app data must be cleared.

Note that the back button does work properly if you **don't** close the app while on the login screen.

**To Reproduce**
1. Clear Findroid app data
2. Open Findroid
3. Choose a server to proceed to the login screen
4. Open app switcher and swipe away Findroid
5. Reopen Findroid
6. Observe that back button does nothing when pressed

**Expected behavior**
Expected behavior is that the back button works at all times to permit reselecting the server.

**Device info:**
 - Device: Samsung Galaxy S21
 - Android version: 12
 - App version: 0.8.0
 - Jellyfin version: 10.8.8

**Comment by imagerss** [comment]
any temporarly workaround? my jellyfin server changed and now i cant connect to it in app, reinstaling app does nothing and i dont know where app stores its data on android

**Comment by jarnedemeulemeester** [comment]
I already have an idea on how to fix this.

On app launch:
If user has no servers bring them to `AddServerFragment`.
If user has a server but is not logged in bring them to the `ServersSelectFragment` where they can remove the server or add an other one.
If user has a server and is logged in bring them to the `HomeFragment`.

**Comment by Natanel-Shitrit** [comment]
@davemsh @realSZ27
Hey, I've implemented a fix!

I've tested it but you are welcome to test it yourself 😄
