### ISSUE TITLE
Aspect ratio issue

### ISSUE THREAD

**Issue by dfunkt** [jarnedemeulemeester/findroid#24]
**Describe the bug**
The aspect ratio seems to be different when compared to the official Jellyfin app, the content is not displayed over the punch-hole camera area.

**To Reproduce**
1. Play video in a cinematic aspect ratio

**Expected behavior**
Video should cover the full screen, going over the punch-hole camera area.

**Screenshots**
![Screenshot_20210825-171532](https://user-images.githubusercontent.com/17910432/130808341-6aa7d990-f379-47cd-9148-166288043ffe.png)
This is from the official app ^^

![Screenshot_20210825-171656](https://user-images.githubusercontent.com/17910432/130808375-3134a461-6267-4458-8d6e-d3adbf64b704.png)
Findroid here ^^

**Device info (please complete the following information):**
 - Device: Poco F3
 - Android version: 11
 - App version: v0.1.1 (2)

**Comment by jarnedemeulemeester** [comment]
Fixed in v0.2.0
