### ISSUE TITLE
Next episode is played back regardless of Autoplay setting

### ISSUE THREAD

**Issue by IgitBuh** [jarnedemeulemeester/findroid#242]
**Describe the bug**
There is a user specific option to enable or disable autoplay at the end of an episode. While the official app works as configured, Findroid doesn't respect that option. The option is disabled, but Findroid always automatically plays the next episode.

**To Reproduce**
1. Make sure the option "Playback" > "Play next episode automatically" is disabled for this user.
2. Play an episode in Findroid till the end (you can skip to short before the end).

**Expected behavior**
Playback should stop and close the player. Instead, the next episode is automatically started.

**Device info (please complete the following information):**
 - Tested on multiple new and some older smartphones and tablets.
 - App version: 0.8.0 (14)
 - Jellyfin version: 10.8.4

**Comment by jarnedemeulemeester** [comment]
Oh I didn't know that option existed haha. I will take a look at fixing it later today

**Comment by IgitBuh** [comment]
Thanks!
Ideally, you could add an option to the app preferences that represents this settings for the current user, allowing to change it (applying it to the profile on the server). That way it could be easily changed directly from the app (sometimes it might be useful to turn it on, sometimes off).
