### ISSUE TITLE
Offline playback broken, caused by introskipper .

### ISSUE THREAD

**Issue by WrobotGames** [jarnedemeulemeester/findroid#261]
**Describe the bug**
After downloading some videos, its impossible to play them offline while having introskipper enabled. Tried both Exoplayer and MPV.
Related to #248

**To Reproduce**
Have introskipper enabled.
Download any video.
Go offline.
Try to watch it.

**Expected behaviour**
Being able to watch the video

**Device info**
 - Device: Samsung A52 4g
 - Android version: 13
 - App version: 0.10.0
 - Jellyfin version: 10.8.9

**Comment by Jcuhfehl** [comment]
Could you try disabling introskipper, the behavior seems similar to the bug I fixed in #248, so it might be related.

**Comment by WrobotGames** [comment]
> Could you try disabling introskipper, the behavior seems similar to the bug I fixed in #248, so it might be related.

That's indeed the problem.
