### ISSUE TITLE
[Feature Request] Setting to disable seek gesture

### ISSUE THREAD

**Issue by Maxplosion** [jarnedemeulemeester/findroid#265]
when turning on gestures (e.g. for brightness and volume) there is no way to turn of the seeking gesture.

this collides with android gestures for "back" if they are set to be "swipe from edge of screen".

so my request would be to add such a setting to enable/disable the seeking gesture by itself.

**Comment by Hjaelp** [comment]
> this collides with android gestures for "back" 

I think it might also need gesture exclusion for the sides, @jarnedemeulemeester ?
On my phone I don't face this issue with the gesture happening if I want to exit playback, but it probably can happen on some phones.

**Comment by Maxplosion** [comment]
if it helps I'm using a galaxy fold 4.

**Comment by Hjaelp** [comment]
> if it helps I'm using a galaxy fold 4.

Can you try changing the gesture sensitivity in your android settings and see if it still triggers the seek gesture as well?

**Comment by Maxplosion** [comment]
I had it already on the second lowest level, using the lowest is kind of the same.

i need to be very precise and really swipen from the furthes pixel to not trigger the seek. 

so yeah maybe limiting the area of the seek gesture would be a good idea. using just the center and 25% around it should be more than enough.

**Comment by jarnedemeulemeester** [comment]
I will take a look at adding gesture exclusion zones to the sides. 
But adding the option to disable the seek gesture separately is also a nice addition :)

**Comment by Maxplosion** [comment]
absolutely

personally I'm not a fan of using gestures for seek so prefer to just turn it off altogether.

but for those who like seeking like that the exclusion zones will for sure be helpful.
