### ISSUE TITLE
[mpv backend] Circle loading icons doesn't disappear

### ISSUE THREAD

**Issue by zx900930** [jarnedemeulemeester/findroid#271]
**Describe the bug**
Circle loading icons doesn't disappear.
![image](https://user-images.githubusercontent.com/734749/216758536-fc189b00-13e7-477a-9f9a-887ca6223c02.png)

**To Reproduce**
1. Use MPV as backend.
2. Play any video and click the progress bar where there is no buffer available yet.
3. Once the circle loading icon appears, it won't disappear.

**Expected behavior**
The circle loading icon will disappear when reaching certain amount of stream buffer time.

**Screenshots**
![Screenshot_2023-02-04-09-41-22-1988635298](https://user-images.githubusercontent.com/734749/216758163-1119631b-00a4-4be3-adf1-1b3628da3589.png)

**Device info (please complete the following information):**
 - Device: [e.g. Google Pixel 3]
 - Android version: [11]
 - App version: [v0.10.1]
 - Jellyfin version: [10.8.9]

**Additional context**
Only happening using mpv.

**Comment by Hjaelp** [comment]
Does this happen with software decoding as well?

Also are you using any mpv.conf configuration?

**Comment by zx900930** [comment]
> Does this happen with software decoding as well?
> 
> Also are you using any mpv.conf configuration?

I'll do some test with software decoding. I dont using any mpv.conf.

**Comment by jarnedemeulemeester** [comment]
The issue with the stuck loading icon should now be fixed (together with some other mpv stuff).
Will be in v0.11.0
