### ISSUE TITLE
Findroid 0.9.0(15) so slow, always not responding and barely usable now

### ISSUE THREAD

**Issue by fmchris10** [jarnedemeulemeester/findroid#272]
**Describe the bug**
When I load the app, it takes about 20/30 seconds to load the main menu/home screen.

Pressing on content pages takes almost a minute to load the details.

The play button spins a circle for about 5 seconds, before loading the player, which spins for about the normal time.

When I exit content, the app freezes, and then I get a pop-up asking me to force close, wait or report [I have sent the report info via email].

I have to literally close the app to get it working again.

In addition, I have a large film library and it's so slow now to navigate. It was instant before, now I'm lucky if it doesn't get stuck on [C] titles.

Adjusting the request timeout, connect timeout and socket timeout helped somewhat, but the previous version worked completely fine. Things loaded up promptly; I could navigate menus and into content without a fuss.

I know this is early development but version 0.9.0(15) is terrible for me.

The previous version was smooth, barely any lag and what was there I put down to being caused through my remote content. From a joyful experience which solved so many playback issues with the official app to something that wants to choke out all the time. I don't get why.

**To Reproduce**
I have no idea how you can replicate this, I have a bog-standard chinese box running Android 8.1.0 - it worked perfectly fine with previous versions of Findroid. I much preferred it over the official app, but I can't use Findroid now.

**Expected behavior**
Load content promptly, no freeze, not take ages to load content information etc.

**Screenshots**
It's like JustEat asking customers to take pictures of cold food. I can share screenshots but they don't show what's happening, I could video record my experience. I might do that if it would help.

**Device info (please complete the following information):**
Sunvell T9
8.1.0
 Findroid 0.9.0(15)
Jellyfin version: 10.7.7-1-ls151
Ethernet connected: average speed of 50mbps uploads a round 17mbps.

I can use the official app to browse fine, like every other streaming app I have from YouTube, ITVX, BBC iPlayer, Virgin Media Go, Prime Video etc.

**Comment by jarnedemeulemeester** [comment]
This is really strange. v0.9.0 does not have any significant changes that would impact performance much.

I see that you are running Jellyfin 10.7.7, the minimum supported version by Findroid is 10.8.1. I highly recommend you upgrade to 10.8.9.

If upgrading your server does not help you can also try clearing the apps storage and setting it up again.
