### ISSUE TITLE
Add software decoding support 

### ISSUE THREAD

**Issue by xd003** [jarnedemeulemeester/findroid#28]
Even though ffmpeg support is present , i can confirm that currently there's no software decoding support in Exoplayer used by findroid . Hevc playback support isn't really great in my android device . Some hevc videos which are playable through hw decoding play well in findroid but the other ones simply fail to play . For reference , i can play all these videos through in Jellyfin official app with external player using software decoding . On top of that , Emby's Exoplayer has support for software decoding so all my videos play well there without any need of external players . I hope you could add this thing , its really useful & helps to avoid transcoding as much as possible. Eventually the player should play each video through hardware decoding at first & fallback to software decoding if the playback initially failed

Android 10
Findroid v0.1.2

**Comment by jarnedemeulemeester** [comment]
The ffmpeg extension for exoplayer only works for audio. There is no video decoder available.

That said I have been trying to get libmpv working in the app to support all video, audio and subtitle codecs

**Comment by jarnedemeulemeester** [comment]
I have implemented mpv player which tries to use hardware decoding with software decoding as a fallback.
