### ISSUE TITLE
Error loading data

### ISSUE THREAD

**Issue by Gottarocket** [jarnedemeulemeester/findroid#3]
No error thats the issue atleast a log file should be showing whats the issue on app end 
Home page shows same error loading data 

Loads fine on server end

**Comment by jarnedemeulemeester** [comment]
Yeah error handeling still needs some work, at least it shouldn't crash. 😄 

Do all screens give the error message? Or only when you do a specific action?

**Comment by Gottarocket** [comment]
Just home page 
Sorry I should report the first day I tried but accessing home provides me trailer and both movies and shows .
Movies and shows also doesnt show separately but will try to add another issue later but this is the priority

**Comment by jarnedemeulemeester** [comment]
No problem man!

Is there any way you could give me access to your Jellyfin instance? That way I can test it and figure out what the problem is.
If you can, just email me the url and login credentials. (jarnedemeulemeester@gmail.com)
Or Reddit dm whatever you prefer. (JDTechn0)

If not then no problem, but I really have no idea what the issue could be.

**Comment by Gottarocket** [comment]
Its running on local server so cant provide you links as external access isnt setup yet and Ill wait for the error log on app or accurate error throwing setup is implemented on next update

**Comment by jarnedemeulemeester** [comment]
No problem, I totally understand!

Detailed error messages are available in v0.1.1 :)

**Comment by Gottarocket** [comment]
Connect timeout has expired [url=http://192.168.x.xx:8096/Sessions/Capabilities?playableMediaTypes=Video&supportedCommands=VolumeUp%2CVolumeDown%2CToggleMute%2CSetAudioStreamIndex%2CSetSubtitleStreamIndex%2CMute%2CUnmute%2CSetVolume%2CDisplayMessage%2CPlay%2CPlayState%2CPlayNext%2CPlayMediaSource&supportsMediaControl=true&supportsSync=false&supportsPersistentIdentifier=true, connect_timeout=6000 ms]

**Comment by Gottarocket** [comment]
This is the error produced

**Comment by jarnedemeulemeester** [comment]
Seems like the app has trouble connecting to your server.

Do other screens work?
What version of Jellyfin are you running?
Maybe try removing the server and adding it again. `Settings -> Manage servers -> Long press server -> Remove`
Or you could try clearing all app data.

**Comment by Gottarocket** [comment]
New update

**Comment by Gottarocket** [comment]
fa.c: Invalid HTTP status in response: 500

**Comment by Gottarocket** [comment]
On home page also shows look good but when you click play apps closes

**Comment by Gottarocket** [comment]
Thanks it works on new update plays better than it does on jellyfin app . Hope mpv stable works better as it does crash on my end

**Comment by Gottarocket** [comment]
Would love anything automated or in app settings to fix the issue. When this issue happens clearing all app data should be the last  option.
