### ISSUE TITLE
Black screen in mpv when subtitles are disabled

### ISSUE THREAD

**Issue by Jcuhfehl** [jarnedemeulemeester/findroid#306]
**To Reproduce**
1. Use findroid compiled from master
2. Enable mpv player
3. Play any video
4. Turn off subtitles
5. No video is displayed and audio keeps playing. The video doesn't return even if subtitles are enabled again.

**Expected behavior**
The video is displayed normally.

**Screenshots**

**Device info (please complete the following information):**
 - Device: ROG Phone 6
 - Android version: 12
 - App version: git master
 - Jellyfin version: 1.8.9

**Additional context**
The problem was introduced in 1a8e71a8a9d93945b11a37bdc1397049ba73fefa, reverting it fixed the issue for me, but I can't figure out why it causes this issue.

**Comment by jarnedemeulemeester** [comment]
This is a pretty big issue as it seems to not only happen when disabling subtitles but also when changing any other track, including audio tracks.

I also have not been able to figure out what exactly causes the issue.

**Comment by jarnedemeulemeester** [comment]
Removing these lines of code seems to fix the issue.
https://github.com/jarnedemeulemeester/findroid/blob/de5fe13c11f55166a2cd18e07be88ef6a930fbcd/player/video/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt#L199-L201

Will investigate further.

**Comment by jarnedemeulemeester** [comment]
Fixed by commenting out those lines. If anything else breaks please report.

Fixed in #329
