### ISSUE TITLE
Lack of spanish language

### ISSUE THREAD

**Issue by newton181** [jarnedemeulemeester/findroid#31]
The app is entirely in English language. I can help you to translate the string.xml file to es, b+es+419 and es-rMX.

1. Open application
2. All the UI is in english

**Expected behavior**
The UI is in the native language of user.

**Screenshots**
No needed.

**Device info (please complete the following information):**
 - Device: moto G7 Play
 - Android version: Android 10
 - App version: v0.1.1

**Comment by jarnedemeulemeester** [comment]
Sorry for the late response, I've been a bit busy with life.

Thanks for the pull request I will quickly check it and merge when I have time :)
