### ISSUE TITLE
Transcoding server settings are ignored

### ISSUE THREAD

**Issue by njmdietrich** [jarnedemeulemeester/findroid#319]
**Describe the bug**
When forcing server-side transcoding, e.g. because the bitrate for remote streaming is limited, Findroid will ignore this and attempt to direct play the video anyway.

**To Reproduce**
1. Set a remote streaming bitrate limit on the server under settings -> playback -> streaming
2. Connect to Jellyfin from Findroid via a remote ip
3. Play a video exceeding the set bitrate

**Expected behavior**
The video should transcode like it does on all other clients I tested (the official Jellyfin Android client, the Kodi plugin, Jellyfin Media Player, the web client).

**Device info (please complete the following information):**
 - Device: Pocophone F1
 - Android version: 13 (LineageOS)
 - App version: 0.10.1
 - Jellyfin version: 10.8.9

**Additional context**
This might be due to the profile "Direct play all" that Jellyfin reports for the Findroid client.

**Comment by newton181** [comment]
"Supported media items: movies, series, seasons, episodes

-  Direct play only, (no transcoding)"

Transcoding isnt supported in this moment.

**Comment by njmdietrich** [comment]
Yeah, I suppose reading helps lol. I guess I will just say that I would really like for transcoding support to be added and close this issue.
