### ISSUE TITLE
End of support?

### ISSUE THREAD

**Issue by JulioNahum** [jarnedemeulemeester/findroid#32]
It is a question since 12 days have passed since the last update. I know that perhaps programming an application like this is not an easy task but I would very much like a sign of life. Since I can not live without this application from the moment you took it out. I hope you can surprise us

**Comment by dfunkt** [comment]
You should check the "develop" branch, last commit there is from 2 days ago.

**Comment by jarnedemeulemeester** [comment]
Don't worry it's not dead. I'm just a bit busy with life. There are still a lot of things planned!
