### ISSUE TITLE
Download using mobile data not working

### ISSUE THREAD

**Issue by karlkarlng** [jarnedemeulemeester/findroid#321]
I can watch using mobile data and roaming. But I cannot download. It works only when on wifi.

**Comment by maulik9898** [comment]
I am also facing a similar issue. Downloading only works on wifi

**Comment by AnonymousWebHacker** [comment]
Something similar happens to me, my server is local, it is not hosted on the internet, I can only access via wifi or ethernet in a local network.

I realized that the error in the cell phone to download occurs if I do not have internet access on that wifi at the same time.

In other words, if I don't have internet on that wifi, the download manager doesn't download the video, if I have internet access on the wifi, the download manager does work.

It seems to me more an error of the download manager of the cell phone than of the findroid app

**Comment by TnZzZHlp** [comment]
Findroid download videos through the phone's download manager, and MIUI's own download manager will have mobile network download restrictions, you can try to set the phone's own download manager to allow mobile network downloads

**Comment by karlkarlng** [comment]
Ive had a look and I don't think there are any settings for download manager that could be changed. This is on pixel 7

**Comment by AnonymousWebHacker** [comment]
> Ive had a look and I don't think there are any settings for download manager that could be changed. This is on pixel 7

neither for REDMI versions with MIUI

**Comment by newton181** [comment]
> Ive had a look and I don't think there are any settings for download manager that could be changed. This is on pixel 7

Have you checked if Data Saver is ON? Data savers limit mobile data comsumption for all apps, system apps included.

**Comment by karlkarlng** [comment]
> Have you checked if Data Saver is ON? Data savers limit mobile data comsumption for all apps, system apps included.

I have checked and data saver is off while the issue is happening.

**Comment by mathsyx-fr** [comment]
I have the same problem on a Realme x50 (android) even when download on mobile data is enable in settings.

**Comment by AdamBGames** [comment]
I have the same issue on my Pixel 6, anyone got a workaround?
