### ISSUE TITLE
PGSSUB subtitles render incorrectly in ExoPlayer

### ISSUE THREAD

**Issue by DrSchottky** [jarnedemeulemeester/findroid#322]
**Describe the bug**
On some videos (some works fine) PGSSUB subtitles are not rendered correctly with ExoPlayer, looks like only the border is rendered.
It always works fine with MPV

**To Reproduce**
1. [Download the attached sample video](https://github.com/jarnedemeulemeester/findroid/files/10983508/Test.Frame.zip) and load it in Jellyfin
2. Turn off mpv from Settings->Player
3. Reproduce the file with subtitles turn on

**Expected behavior**
Subititles properly rendered

**Screenshots**
***Subtiltes with ExoPlayer***
![exo](https://user-images.githubusercontent.com/6048264/225409374-d4d1dad9-4c64-477f-b1b3-258224327d60.jpg)
***Subtitles with MPV***
![mpv](https://user-images.githubusercontent.com/6048264/225409454-e4ddca41-0cd1-4a7f-b5f1-3ac754e8126b.jpg)

**Device info (please complete the following information):**
 - Device: Google Pixel 3A
 - Android version: 12
 - App version: 0.10.1 (17)
 - Jellyfin version: 10.8.9

**Comment by jarnedemeulemeester** [comment]
Tested and seems to work fine.
I will assume this has been fixed with newer versions of androidx.media3 (exoplayer)
