### ISSUE TITLE
Google Play Version of the app is broken on my Galaxy A53

### ISSUE THREAD

**Issue by NicholasFlamy** [jarnedemeulemeester/findroid#335]
Exoplayer refuses to play and mpv loads about every 5th frame. The Galaxy A53 (my phone) has the Exynos 1280 so that might be part of it. If I download Findroid off of IzzyOnDroid it works fine. Maybe Google screwed something up? I swear it use to work.

**Comment by NicholasFlamy** [comment]
Now the problem started happening on both versions wtf. It must be a problem with Jellyfin since Exoplayer as part of the Jellyfin app also behaves the same where it won't play.

**Comment by jarnedemeulemeester** [comment]
Maybe it has to do with the codec of the videos you are trying to play. What codec and bit-depth are they?

**Comment by NicholasFlamy** [comment]
It's because the Galaxy A53 supports mkv but it say 4K30 and so basically 4K24 H.265 is too much for it. Lmfao I'm an imbecile. 1080p or 4K H.264 works lol.

**Comment by NicholasFlamy** [comment]
Apparently HEVC support on this phone is bugged. Aww dang. 
https://www.reddit.com/r/PleX/comments/wqlgpy/hevc_playback_samsung_galaxy_a53/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by NicholasFlamy** [comment]
#550
