### ISSUE TITLE
Abnormal clarity selection for multi version video playback

### ISSUE THREAD

**Issue by icfy-dmc** [jarnedemeulemeester/findroid#343]
**Describe the bug**
Abnormal clarity selection for multi version video playback

**To Reproduce**
1.Open the homepage of movies with multiple versions
2.Click the play button

**Expected behavior**
Pop up version selection, click on the target version and play it

**Device info (please complete the following information):**
 - Device: xiaomi 12s pro
 - Android version: 13
 - App version: 0.10.1
 - Jellyfin version: 10.8.9

[Video Description](https://temp-1256883275.cos.ap-nanjing.myqcloud.com/50_1682316759.mp4)

**Comment by jarnedemeulemeester** [comment]
I see that there is indeed an issue with selecting the video version. 
I have already fixed it and will be available in the next version :smile:
