### ISSUE TITLE
Error when start an episode

### ISSUE THREAD

**Issue by ZipName80** [jarnedemeulemeester/findroid#347]
**Describe the bug**
An error appears when launching an episode

**To Reproduce**
1. Launch Findroid
2. Play a movie or a series
3. See error

**Expected behavior**
Start the series

**Screenshots**
![Screenshot_2023-05-01-15-19-44-91_aff99014c254344a005aaf8c1683039d](https://user-images.githubusercontent.com/52377140/235457481-55fd2416-cb90-4e07-b1b2-73a3c7795ab0.jpg)

**Device info (please complete the following information):**
 - Device: Oppo Find X3 Lite
 - Android version: 13
 - App version: 0,10,1 (17)
 - Jellyfin version: 10.8.10

**Comment by jarnedemeulemeester** [comment]
I may have already fixed this issue in the next update. That update should go live within the next week.
There should also be a "View details" button to show the detailed error. I made sure the button is there in the next release.

I will @ you when the update is released

**Comment by PoorPocketsMcNewHold** [comment]
Can confirm it got fixed in the upcoming update, when testing it with the latest debug builds.
For me, it spouted an error on anything with : 
```
Invalid HTTP status in response: 500
 ua.c: Invalid HTTP status in response: 500
	at ta.e.l(Unknown Source:516)
	at ta.e$d.q(Unknown Source:17)
	at b9.a.i(Unknown Source:8)
	at kotlinx.coroutines.p0.run(Unknown Source:100)
	at kotlinx.coroutines.internal.g.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.l.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
```

**Comment by jarnedemeulemeester** [comment]
@ZipName80 v0.11.0 has been released. Could you update the app and see if the issue disappears?

**Comment by ZipName80** [comment]
I just updated the application and it works great, thank you so much for your time and work behind it.
