### ISSUE TITLE
Error playing with experimental MPV player

### ISSUE THREAD

**Issue by JulioNahum** [jarnedemeulemeester/findroid#35]
**Describe the bug**
The same update says so. The experimental MPV player is experimental. But almost nothing reproduces there. I know it is a good step to have a player with a lot of codec support but so far it is that, experimental. We greatly appreciate your dedication to this project. The new player interface is perfect. I know you will keep updating it and we look forward to more improvements and new features.

**To Reproduce**
1. Activate the experimental player from the settings.
2. Try to play content
3. The screen goes into playback mode but the application closes automatically.

**Device info:**
 - Device: [LG K61]
 - Android version: [10]
 - App version: [0.2.0]

**Comment by jarnedemeulemeester** [comment]
This should be fixed in v0.2.1, if not feel free to open this again

**Comment by Maxplosion** [comment]
works now for me!
