### ISSUE TITLE
Feature request: Show item's file size

### ISSUE THREAD

**Issue by Rdkang** [jarnedemeulemeester/findroid#363]
It would be great if the file size of the item could be shown in the item meta data chips so that it can be seen before downloading and playing.

As a user would want to know how much space a downloaded item would take.
Or if streaming over a metered plan how much data it would use.

**Comment by jarnedemeulemeester** [comment]
#367 implements this as an extra line when "Display extra info" is enabled in the appearance settings.

**Comment by Rdkang** [comment]
@Yash-Garg thank you :)
