### ISSUE TITLE
Can't add server on local network

### ISSUE THREAD

**Issue by AKDub** [jarnedemeulemeester/findroid#37]
Its possible I've not put in the right format, but I've tried every format I can think of (maybe a hint can be added to the login screen). 

Any ideas? The regular Jellyfin app finds the server with no issue so I presume that's all configured correctly.

**Comment by jarnedemeulemeester** [comment]
Hmm that's strange, I tested a lot of formats and all of them seem to work.
Some examples:
- 192.168.x.x
- http://192.168.x.x
- https://192.168.x.x
- 192.168.x.x:8096
- etc

What format are you trying to use?
The system to detect the jellyfin server from the input address is provided by the official jellyfin kotlin sdk.
