### ISSUE TITLE
reduce rating to n.n instead of n.nnn format

### ISSUE THREAD

**Issue by foss-** [jarnedemeulemeester/findroid#370]
The rating current uses three digits after the `.` while one would be sufficient.

<img src="https://github.com/jarnedemeulemeester/findroid/assets/5708172/10e4ee58-5881-4bee-a39e-c8f38492661e" width="400">

 - Device: Gauguin
 - Android version: 13
 - App version: 0.11.1 (19)
 - Jellyfin version: 10.8.10

**Comment by Natanel-Shitrit** [comment]
Round up? Round down?
I think it's perfect with the way it is :)

It's a personal preference - I'm sure it would be nice to have an option to change it!

But I think the settings menu will be too crowded if every little detail will be customizable - that should be taken into consideration.

**Comment by foss-** [comment]
@Natanel-Shitrit can you elaborate which influence the third digit after the dot has on you, when you are checking a Rating?

**Comment by Natanel-Shitrit** [comment]
It doesn't really bother me if it's 1 number or 3 after the decimal point.

I just think that if it's reduced to 1 number - you may or may not round the rating.

This does effect the rating because for me I don't find it accurate anymore if it's suddenly rounded.

This is just my opinion 🙂

**Comment by tippfehlr** [comment]
I would just cut them of. I agree to the proposal, the rating isn't meaningful enough for hundredths of stars anyways.
