### ISSUE TITLE
Content aren't ordered by alphabetical number

### ISSUE THREAD

**Issue by Ge082** [jarnedemeulemeester/findroid#38]
** Describe the issue **
Content aren't ordered in alphabetical number

** How to reproduce **
Simply go to a library, TV Shows and Movies are concerned

** Screenshot **
![Screenshot_20211001-124447_Findroid](https://user-images.githubusercontent.com/76789478/135608425-fad1a2ee-f7c8-47cd-9d96-c910343cc50e.jpg)

** Additionnal info **
Might be due to the library size ? (600 movies)
I just modified the code to allow more items per row, 2 movies is a little for the size of my library, no other stuffs was modified

**Comment by jarnedemeulemeester** [comment]
Yes I agree, the list should be in alphabetical order. 
Currently it just displays the items in the order received from the server.
I will add sorting options with alphabetical as the default :)
