### ISSUE TITLE
[feature request]Long Press the player screen to multiply speed by 2.0

### ISSUE THREAD

**Issue by smarttommyau** [jarnedemeulemeester/findroid#386]
As title described, long pressing on the player's screen to multiply speed by 2.0, and go back to normal speed when finger released.

**Comment by peerless2012** [comment]
Same FR and this feature is very useful. 
And normally long press is 3x speed，if can config by user is more perfect.

**Comment by peerless2012** [comment]
This feature seems not support for media3 library and I create a [FR](https://github.com/androidx/media/issues/924) for media3 library for Android team. 

And at this time, we may need to do the spped up for long press by our sefl.

**Comment by peerless2012** [comment]
This issue should close as the feature is finished and released already.
