### ISSUE TITLE
Image won't Update 

### ISSUE THREAD

**Issue by Bugreporter48** [jarnedemeulemeester/findroid#392]
**Describe the bug**
The image won't update in the app.

**To Reproduce**
1. Go to "Edit Image".
2. Change primary image to a newer one.
3. Refresh metadata of jellyfin.
4. See if the image is change in the app.

**Expected behavior**
Changing the primary image to the newer one.

**Screenshots**
![showcase](https://github.com/jarnedemeulemeester/findroid/assets/127946441/44a731e8-377d-4c33-8108-91faf52c61df)

**Device info**
 - Device: [Google Pixel 5]
 - Android version: [13]
 - App version: [0.11.1]
 - Jellyfin version: [10.8.10]

**Comment by jarnedemeulemeester** [comment]
Fixed in #388 

Fix will be in the next release
