### ISSUE TITLE
Finish watching something offline doesn't remove the progress of the item.

### ISSUE THREAD

**Issue by JVT038** [jarnedemeulemeester/findroid#406]
**Describe the bug**
When I finish watching a movie / episode offline, it breaks the progress on the Jellyfin server.
After syncing, the Jelyfin server will show that the item has been watched, but it will keep the progress.
In the screenshot below, it shows a checkmark, which means that it has been watched. However, it also shows the blue progress bar, meaning that the item is still in progress.
This causes the watched items to be in the 'continue watching' row, because the Jellyfin server has the item marked as in-progress.

**To Reproduce**
1. Go to an item.
2. Download the item.
3. Watch the item offline
4. Sync the item by going back online.
5. See error.

**Expected behavior**
I expected the item to be properly synced and not with in-progress status.

**Screenshots**
![image](https://github.com/jarnedemeulemeester/findroid/assets/47184046/398735b8-472a-42ae-b031-6fdf78e4b196)

**Device info (please complete the following information):**
 - Device: Fairphone 4
 - Android version: 12
 - App version: 0.12.0
 - Jellyfin version: 10.8.10

**Comment by Natanel-Shitrit** [comment]
Can confirm: 
![image](https://github.com/jarnedemeulemeester/findroid/assets/65548905/13071020-1bc2-4fe5-ae2c-312f676d5d49)

Should be fixed by a simple update to the time of the item :)

**Comment by Natanel-Shitrit** [comment]
Might be related? (not sure)
- #465

**Comment by Natanel-Shitrit** [comment]
I think this issue has been resolved, but because the PR was not linked it didn't close the issue.

@jarnedemeulemeester
