### ISSUE TITLE
When a call comes in while I'm watching a video, progress jumps back to where it was before.

### ISSUE THREAD

**Issue by yeungchie** [jarnedemeulemeester/findroid#412]
**Describe the bug**

When a call comes in while I'm watching a video, progress jumps back to where it was before.

当我正在看视频的时候有电话打进来，进度就会跳回到之前的位置。

**Device info (please complete the following information):**
 - Device: Xiaomi 12 pro
 - Android version: 12 (MIUI14)
 - App version: 0.11.1
 - Jellyfin version: 10.8.9

**Comment by anvishinc** [comment]
Having the same issue, and this issue also occurs when you lock the screen manually or when you leave the player paused and the screen timeouts. It gets super annoying when you have to manually exit the player and only then will the progress be saved or else be lost.

**Comment by Natanel-Shitrit** [comment]
This should've been fixed by a recent commit 7a3b67f64b2680bdac939fed70a32c377cdde0f9.

If you are willing to test, please download the [APK from the artifacts](https://github.com/jarnedemeulemeester/findroid/actions/runs/5500066413) and report back 😄

**Comment by anvishinc** [comment]
It's working fine now. 👍As the commit is in master, I think I will just move to the latest release and use it instead

**Comment by Natanel-Shitrit** [comment]
Next release will ship the fix, thanks for confirming 🙂

**Comment by yeungchie** [comment]
The latest release has been fixed this bug.
thx.
