### ISSUE TITLE
App "locks" itself when url changes.

### ISSUE THREAD

**Issue by realSZ27** [jarnedemeulemeester/findroid#414]
**Describe the bug**
If the url you use for the server changes for any reason you cannot change the server from the login screen.

**To Reproduce**
1. Setup one url in findroid (eg. jelly.example.com)
2. Change/delete that url (eg. jellyfin.example.com)
3. Try to open findroid.

**Expected behavior**
Ability to change the server from the login screen.

**Device info (please complete the following information):**
 - Device: Samsung S20FE
 - Android version: 13
 - App version: v0.12.0
 - Jellyfin version: 10.8.10

**Comment by Natanel-Shitrit** [comment]
#235 might be related or even the same problem

**Comment by Natanel-Shitrit** [comment]
@realSZ27 Could you confirm or deny if this is the same issue as #235?

**Comment by realSZ27** [comment]
Yes, I think it is. If not exactly, the solution would definitely be the same.

**Comment by Natanel-Shitrit** [comment]
Alright, thanks for confirming.

Could you close this issue so we can keep track of the issue in the original issue?

I'll try to work on a fix soon 😃
