### ISSUE TITLE
Feature request: Show show's episode size in extra info

### ISSUE THREAD

**Issue by Rdkang** [jarnedemeulemeester/findroid#452]
> It would be great if the file size of the item could be shown in the item meta data chips so that it can be seen before downloading and playing.

> As a user would want to know how much space a downloaded item would take.
Or if streaming over a metered plan how much data it would use.

The same problem in #363 but for tv shows episode.

This has been done for movies in #367 and would be great if this could be added for shows as well :)

**Comment by Rdkang** [comment]
@Yash-Garg you up for this? :smiley_cat: :purple_heart:

**Comment by Yash-Garg** [comment]
> n new issue
> [ Report content ](/contact/report-content?content_url=https%3A%2F%2Fgithub.com%2Fjarnedemeulemeester%2Ffindroid%2Fissues%2F452%23issuecomment-1656768321&report=Rdkang+%28user%29)

@Rdkang will try to check it in the weekend if I get time!
