### ISSUE TITLE
When I turn off the screen while watching, the playback time is reset.

### ISSUE THREAD

**Issue by KimPig** [jarnedemeulemeester/findroid#455]
**Describe the bug**
While watching the video, when I press the power button and turn the screen off and on again, the video plays from the beginning.

**To Reproduce**
1.Watch any video
2.Trun the screen off by pressing power button
3.Turn it on
4.Watch the bug

**Expected behavior**
It should be played continuously from the last playtime.

**Device info (please complete the following information):**
 - Device: Xiaomi 13
 - Android version: 13
 - App version: 0.12.0
 - Jellyfin version: 10.8.10

**Comment by jarnedemeulemeester** [comment]
This has already been fixed with 7a3b67f64b2680bdac939fed70a32c377cdde0f9 
The fix has not been released yet but will be in the next version!
