### ISSUE TITLE
[Feature Request] Optionally use an good accessible download location

### ISSUE THREAD

**Issue by MarkusTieger** [jarnedemeulemeester/findroid#462]
Instead of using Android/data as storing location for downloaded movies, would it be handy if you could also optionally use it in a more accessible location. eg I'm going on vacation tomorrow and there I have no internet, so I deleted all the movies from Findroid and re-downloaded to another location, because otherwise I can not use it with the VLC to use it with my chromecast, which does not require internet with vlc. Best also not save with the Id's but with the original filenames on the server.

**Comment by Natanel-Shitrit** [comment]
Related:
- #108
- #453 

See [my suggestion](https://github.com/jarnedemeulemeester/findroid/issues/453#issuecomment-1673949043) in #453.
