### ISSUE TITLE
Feature request  Offline mode toggle in the downloads screen

### ISSUE THREAD

**Issue by lambchop01** [jarnedemeulemeester/findroid#470]
Would it be possible to put a toggle for "Offline Mode" in the downloads screen.  Both of the tablets i use do not show the "switch to offline mode" popup (for lack of a better word) and going into the settings is a couple steps too many for my kids.

Maybe better yet, could the downloads screen always behave as if offline mode is toggled? no need to show the splash screen for the movie/show there, just the ability to play the media.

**Comment by Natanel-Shitrit** [comment]
Related:
- #473

Would that be acceptable for this request?

**Comment by Jcuhfehl** [comment]
Well I'm kinda afraid that if the switch to offline popup doesn't appear for @lambchop01 the option to switch automatically won't work either, since it's the same code that checks connectivity. But ofc I can't be sure because I can't reproduce their issue

**Comment by lambchop01** [comment]
@jarnedemeulemeester is there a way to get the logs and see what is happening on the tablet?  I'd be happy to share them here if that would help

**Comment by Natanel-Shitrit** [comment]
> Well I'm kinda afraid that if the switch to offline popup doesn't appear for @lambchop01 the option to switch automatically won't work either, since it's the same code that checks connectivity. But ofc I can't be sure because I can't reproduce their issue

IIRC there is no "offline mode popup", and that's why it doesn't "work".

On a general note, I think keeping the downloads tab accessible when the server isn't working *is* a good idea.

**Comment by lambchop01** [comment]
![Screenshot_20230818-152814.png](https://github.com/jarnedemeulemeester/findroid/assets/62576245/f6e1b7e2-dff2-41bf-8259-9e3a4a87a6da)

@Natanel-Shitrit  @jarnedemeulemeester 

This is the "popup" I'm referring to across the bottom of the screen. It works perfectly well on my phone just not on the tablets.

I agree with your second point Natanel. Having the downloads tab accessible at all times would be beneficial.

**Comment by Natanel-Shitrit** [comment]
First time seeing this popup 😮
Good to know!

I wonder why this is only showing on the "Downloads" tab and not (also) in the "Home" tab 🤔

**Comment by Natanel-Shitrit** [comment]
I was able to reproduce the problem with the a virtual android device.
I'll see if I'm able to make the popup appear on tablets too.

**Comment by lambchop01** [comment]
Awesome! Best of luck 😀😉

**Comment by Natanel-Shitrit** [comment]
Pinned down the problem to this thing:
https://github.com/jarnedemeulemeester/findroid/blob/cef6bf3c0a84d233fef8e91ceed30f6b1a622697/app/phone/src/main/java/dev/jdtech/jellyfin/fragments/DownloadsFragment.kt#L61

I have no idea why this is causing the snackbar to not show in tablets but it seem to work fine in mobile & tablet without this.

**Comment by Jcuhfehl** [comment]
I'm guessing it's because the nav view is on the side on tablets. I can now also reproduce this by using my phone in landscape mode

**Comment by Natanel-Shitrit** [comment]
> I'm guessing it's because the nav view is on the side on tablets. I can now also reproduce this by using my phone in landscape mode
> 
> Edit: also this means that the automatic switcher works on all devices, since this code has nothing to do with that

Great, thanks for the explaination!

However, there is still one small problem with tablets that I'll try to fix before PRing this change.
The snackbar text is getting cut off because it's too long.

Funny that's happening on tablet view which supposed to be bigger normal view 😆

**Comment by Natanel-Shitrit** [comment]
And..... Fixed!
![image](https://github.com/jarnedemeulemeester/findroid/assets/65548905/b463ce1c-0a7f-4845-a593-a5b5fed6093f)

**Comment by Natanel-Shitrit** [comment]
Thanks for the help @Jcuhfehl!
Will PR now :)
