### ISSUE TITLE
[Feature request] Sorting episodes by newest.

### ISSUE THREAD

**Issue by Margit420** [jarnedemeulemeester/findroid#479]
The ability to sort episodes by oldest/newest like Crunchyroll.

![Picsart_23-08-20_07-27-23-665](https://github.com/jarnedemeulemeester/findroid/assets/113560376/e57449d3-eea7-49ac-80f3-65d53618fc2c)
ll 

![Screenshot_2023-08-20-07-36-57-74_67cf7b0a532dfd6f5b3d38685d9b835b](https://github.com/jarnedemeulemeester/findroid/assets/113560376/5917df99-09e9-4e30-8c04-2a844b5d865c)

**Comment by Natanel-Shitrit** [comment]
Sounds like a great request, I'll try to make something.

**Comment by Natanel-Shitrit** [comment]
![Screenshot_20230820-225417~2.png](https://github.com/jarnedemeulemeester/findroid/assets/65548905/3b2524bc-5346-4df9-a169-7c6b5b239860)

Design idea

**Comment by Margit420** [comment]
Looks dope! I really like it

Some seasons have long titles though, so the button should probably be on the top right corner (?)
![Screenshot_2023-08-20-21-40-49-82_aff99014c254344a005aaf8c1683039d](https://github.com/jarnedemeulemeester/findroid/assets/113560376/9cb7bfa4-fd7b-426e-863e-9e25854b8f8f)

Like this
![Picsart_23-08-20_22-37-16-891](https://github.com/jarnedemeulemeester/findroid/assets/113560376/ab596933-9113-4928-87ba-e5ec190f0fc0)

**Comment by Natanel-Shitrit** [comment]
I don't know if I like this 😅
![screen](https://github.com/jarnedemeulemeester/findroid/assets/65548905/6a820919-7d68-40e2-9fbe-0d91f9808705)

**Comment by Margit420** [comment]
Yeah obviously the first one you made looks better, as long as it doesn't cramp up long titles

**Comment by Natanel-Shitrit** [comment]
@Margit420  Final design :) 
![screen](https://github.com/jarnedemeulemeester/findroid/assets/65548905/35f0d4cc-44ee-4809-8ead-ae3307fc13ba)

**Comment by Margit420** [comment]
> @Margit420 Final design :) ![screen](https://user-images.githubusercontent.com/65548905/263282094-35f0d4cc-44ee-4809-8ead-ae3307fc13ba.png)

Looks like a good compromise . Tysm <3
