### ISSUE TITLE
Findroid app can't show media libraries of type "Mixed Movies and Shows"

### ISSUE THREAD

**Issue by xenoncolt** [jarnedemeulemeester/findroid#497]
**Describe the bug**
This is the current version app view where not show "Mixed Movies and Shows"
![WhatsApp Image 2023-08-28 at 17 36 03](https://github.com/jarnedemeulemeester/findroid/assets/81591350/a766c87c-4f85-4405-8817-ff7bb00b28d9)

Here I marked those Movies and shows that are not displayed
![image](https://github.com/jarnedemeulemeester/findroid/assets/81591350/a97f1306-ffd2-49a2-94d1-d71a838bf311)

I hope you understand what I want to say.

**Comment by gjp1120** [comment]
same issue

**Comment by UriSheinman** [comment]
Not really a bug, just a problem with how findroid looks for libraries. It only looks for ones marked as Movies/ Shows and the collections folder. Thats why music won't appear and why mixed folders won't appear. It just doesn't look for them.

**Comment by GreatestFool** [comment]
True enough, though an improperly scoped domain doesn't invalidate the report either. It may not be a bug, but it is a feature that is wanted and sorely lacking. The music and book libraries I can understand, but given that a mixed library is generally used for both TV-shows and Movies, I think it has its place in this application. It's already pretty great, after all.

I do hope we see it implemented someday soon. Though, giving the view models a quick one-over, I'd guess they'd need at least some changes to avoid code-reuse in a model dedicated for mixed libraries. I'd like to say that shouldn't be too hard to implement, but I'm not familiar enough with the code-base to really say anything there.

**Comment by GreatestFool** [comment]
For sake of keeping things _somewhat_ organized, here's other duplicate issues:
- https://github.com/jarnedemeulemeester/findroid/issues/154
- https://github.com/jarnedemeulemeester/findroid/issues/224
- https://github.com/jarnedemeulemeester/findroid/issues/352

Feel free to ignore this message, this is mostly so that these issues are shown to be referenced in this one.
