### ISSUE TITLE
Android TV - Top level menu not showing.

### ISSUE THREAD

**Issue by AKDub** [jarnedemeulemeester/findroid#498]
**Describe the bug**
In the Android TV it seems to open up in the 'Home' section, as I can see the various 'Latest' options on the left. 

**To Reproduce**
Just open the app on Android TV

**Expected behavior**
I presume that there should be a way to switch to the 'My Media', 'Favourites', and 'Downloads' section but I cannot see that option anywhere.

**Device info (please complete the following information):**
 - Device: [LEAP-S1]
 - Android version: [10]
 - App version: [v0.1.2]
 - Jellyfin version: [10.8.10]

**Comment by jarnedemeulemeester** [comment]
Findroid is currently not supported on Android TV.
An Android TV version is in the works.
