### ISSUE TITLE
Battery saver mode resets playback position

### ISSUE THREAD

**Issue by gudvinr** [jarnedemeulemeester/findroid#505]
**Describe the bug**

When phone battery charge goes below certain level, battery saver mode is enabled.  
If you have something playing in findroid player, playback resets to the beginning.

As I mentioned in https://github.com/jarnedemeulemeester/findroid/issues/389#issuecomment-1672351934, it could've been caused by changing theme to "dark", which is controlled by `android:configChanges="uiMode"`.

**To Reproduce**
1. Start playback
2. Discharge battery

**Expected behavior**
Playback doesn't reset or interrupted in any way

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Device info (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Android version: 13
 - App version: 0.13.0
 - Jellyfin version: 10.8.10

**Additional context**
~~Add any other context about the problem here.~~

**Comment by jarnedemeulemeester** [comment]
Added `uiMode` to `android:configChanges`.
This indeed fixes the issue
