### ISSUE TITLE
Detaching the keyboard-cover restarts the file

### ISSUE THREAD

**Issue by Babrr** [jarnedemeulemeester/findroid#510]
When I detach the samsung keyboard-cover the multimedia content restart from beginning.

Samsung Galaxy Tab S7+
Android 13
One UI 5.1.1

**Comment by jarnedemeulemeester** [comment]
I suspect adding `uiMode` to `android:configChanges` also fixes this issue. Hence why I closed it.
This fix will be availeble in the next release (0.13.1).

If the issue still happens op the to be released update, feel free to reopen.
