### ISSUE TITLE
Http error

### ISSUE THREAD

**Issue by starnakin** [jarnedemeulemeester/findroid#532]
**Describe the bug**
i have an http error 500 on certain episode

**To Reproduce**
1. Try to play some episodes of a saison with - some corrupted or missing episode

**Screenshots**
![Screenshot_20231001-200535_Findroid.png](https://github.com/jarnedemeulemeester/findroid/assets/47717174/243f91b0-4101-4895-a525-f653610a034a)

**Device info (please complete the following information):**
 - Device: Google Pixel 2
 - Android version: 12
 - App version: 0.13.1
 - Jellyfin version: 10.8.10

**log**

``` Invalid HTTP status in response: 500
 rb.c: Invalid HTTP status in response: 500
	at qb.f.h(Unknown Source:465)
	at qb.e.s(Unknown Source:17)
	at r9.a.i(Unknown Source:8)
	at d9.m.d(Unknown Source:99)
	at d9.m.b(Unknown Source:15)
	at d9.l.i(Unknown Source:22)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.m.b(Unknown Source:15)
	at d9.l.i(Unknown Source:22)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.m.b(Unknown Source:15)
	at d9.l.i(Unknown Source:22)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.m.b(Unknown Source:15)
	at d9.l.i(Unknown Source:22)
	at r9.a.i(Unknown Source:31)
	at ia.j0.run(Unknown Source:107)
	at androidx.appcompat.widget.j.run(Unknown Source:878)
	at pa.l.run(Unknown Source:2)
	at pa.a.run(Unknown Source:95)

```

**Comment by Natanel-Shitrit** [comment]
Are you able to play the episode in Jellyfin web?

This usually happens to me when my Sonarr is upgrading items - and the Jellyfin server haven't synced the new file. (it is still trying to fetch the old file)

To check if that's your case:
1. Go to Jellyfin server.
2. Go to item and click the 3 dots.
3. Click "Copy Stream URL".
4. Paste the URL in your browser.

If you get status code 500, try to "refresh metadata" then "Scan for new and updated file". (Alternatively, you can "Scan All Libraries" in the dashboard)

If the stream URL works, or you still get status code 500 after refreshing the metadata, there is another problem.

**Comment by Jcuhfehl** [comment]
The thing is that a 500 error is (almost) always a server side error (it's literally internal server error). Maybe we could change the error message to make this clear to users?

**Comment by starnakin** [comment]
> Are you able to play the episode in Jellyfin web?
> 
> This usually happens to me when my Sonarr is upgrading items - and the Jellyfin server haven't synced the new file. (it is still trying to fetch the old file)
> 
> To check if that's your case:
> 1. Go to Jellyfin server.
> 2. Go to item and click the 3 dots.
> 3. Click "Copy Stream URL".
> 4. Paste the URL in your browser.
> 
> If you get status code 500, try to "refresh metadata" then "Scan for new and updated file". (Alternatively, you can "Scan All Libraries" in the dashboard)
> 
> If the stream URL works, or you still get status code 500 after refreshing the metadata, there is another problem.

Thanks for your reply, I have no error with the stream URL, refresh méta data doesn't change

**Comment by starnakin** [comment]
> The thing is that a 500 error is (almost) always a server side error (it's literally internal server error). Maybe we could change the error message to make this clear to users?

I don't have understand if your reply is destinate to my message or if it is global message, but my server don't have visible problem

**Comment by Jcuhfehl** [comment]
> I don't have understand if your reply is destinate to my message or if it is global message, but my server don't have visible problem

No it's general, there are multiple issues about 500 internal server errors, so indicating that it's probably a server issue would point people in the right direction

**Comment by Natanel-Shitrit** [comment]
> > Are you able to play the episode in Jellyfin web?
> > This usually happens to me when my Sonarr is upgrading items - and the Jellyfin server haven't synced the new file. (it is still trying to fetch the old file)
> > To check if that's your case:
> > 
> > 1. Go to Jellyfin server.
> > 2. Go to item and click the 3 dots.
> > 3. Click "Copy Stream URL".
> > 4. Paste the URL in your browser.
> > 
> > If you get status code 500, try to "refresh metadata" then "Scan for new and updated file". (Alternatively, you can "Scan All Libraries" in the dashboard)
> > If the stream URL works, or you still get status code 500 after refreshing the metadata, there is another problem.
> 
> Thanks for your reply, I have no error with the stream URL, refresh méta data doesn't change

Interesting, are you saying that stream URL works and Findroid still returns `500 Error`?
If your server is reachable from the internet, I can try to debug this if you create a temporary user to your server.

**Comment by starnakin** [comment]
> > > Are you able to play the episode in Jellyfin web?
> > > This usually happens to me when my Sonarr is upgrading items - and the Jellyfin server haven't synced the new file. (it is still trying to fetch the old file)
> > > To check if that's your case:
> > > 
> > > 1. Go to Jellyfin server.
> > > 2. Go to item and click the 3 dots.
> > > 3. Click "Copy Stream URL".
> > > 4. Paste the URL in your browser.
> > > 
> > > If you get status code 500, try to "refresh metadata" then "Scan for new and updated file". (Alternatively, you can "Scan All Libraries" in the dashboard)
> > > If the stream URL works, or you still get status code 500 after refreshing the metadata, there is another problem.
> > 
> > Thanks for your reply, I have no error with the stream URL, refresh méta data doesn't change
> 
> Interesting, are you saying that stream URL works and Findroid still returns `500 Error`?
> If your server is reachable from the internet, I can try to debug this if you create a temporary user to your server.

Yes, can send your email or discord ?

**Comment by Natanel-Shitrit** [comment]
> > > > Are you able to play the episode in Jellyfin web?
> > > > This usually happens to me when my Sonarr is upgrading items - and the Jellyfin server haven't synced the new file. (it is still trying to fetch the old file)
> > > > To check if that's your case:
> > > > 
> > > > 1. Go to Jellyfin server.
> > > > 2. Go to item and click the 3 dots.
> > > > 3. Click "Copy Stream URL".
> > > > 4. Paste the URL in your browser.
> > > > 
> > > > If you get status code 500, try to "refresh metadata" then "Scan for new and updated file". (Alternatively, you can "Scan All Libraries" in the dashboard)
> > > > If the stream URL works, or you still get status code 500 after refreshing the metadata, there is another problem.
> > > 
> > > 
> > > Thanks for your reply, I have no error with the stream URL, refresh méta data doesn't change
> > 
> > 
> > Interesting, are you saying that stream URL works and Findroid still returns `500 Error`?
> > If your server is reachable from the internet, I can try to debug this if you create a temporary user to your server.
> 
> Yes, can send your email or discord ?

You can find me in the [Findroid Discord](https://discord.gg/tg5VvTFwTV)
![image](https://github.com/jarnedemeulemeester/findroid/assets/65548905/5c8f2896-ad42-4c93-b961-2d4e04ee5457)
Or just add me: `luqs`

**Comment by Natanel-Shitrit** [comment]
Error log:
```
[2023-10-01 20:34:59.808 +00:00] [ERR] [128] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Items/7008b5ff-ae6b-a341-c3cf-0025a7acc0db/PlaybackInfo".
```

**Comment by Natanel-Shitrit** [comment]
We found the problem :)
![image](https://github.com/jarnedemeulemeester/findroid/assets/65548905/0306b0d2-f9f1-4f47-8334-111b76a55be7)

Remember to put your incomplete files separated from the actual media files!

**Comment by nate-moo** [comment]
> > > Are you able to play the episode in Jellyfin web?
> > > This usually happens to me when my Sonarr is upgrading items - and the Jellyfin server haven't synced the new file. (it is still trying to fetch the old file)
> > > To check if that's your case:
> > > 
> > > 1. Go to Jellyfin server.
> > > 2. Go to item and click the 3 dots.
> > > 3. Click "Copy Stream URL".
> > > 4. Paste the URL in your browser.
> > > 
> > > If you get status code 500, try to "refresh metadata" then "Scan for new and updated file". (Alternatively, you can "Scan All Libraries" in the dashboard)
> > > If the stream URL works, or you still get status code 500 after refreshing the metadata, there is another problem.
> > 
> > 
> > Thanks for your reply, I have no error with the stream URL, refresh méta data doesn't change
> 
> Interesting, are you saying that stream URL works and Findroid still returns `500 Error`? If your server is reachable from the internet, I can try to debug this if you create a temporary user to your server.

All of my files are complete and the files play through the URL.
So far it only affects one series, with another loading the player but no the actual content
