### ISSUE TITLE
Feature Request: Simplified track selection menu for mpv

### ISSUE THREAD

**Issue by UriSheinman** [jarnedemeulemeester/findroid#534]
Mpv player shows the tracks in a very not user friendly way (language codes rather then names). I know you don't develope the players used but is it possible to use a more friendly design for the menus in mpv?
![Screenshot_20230828-231754](https://github.com/jarnedemeulemeester/findroid/assets/132785427/ad1d31ce-dd11-4c1e-b70e-8f9df9ee194f)
Exo👆
![Screenshot_20230828-231731](https://github.com/jarnedemeulemeester/findroid/assets/132785427/470dd10b-9c5d-4869-ae19-bd4773592f96)
Mpv👆
Ideally it would be language, and if the track had a name then the name as well (for stuff like commentery tracks)

**Comment by UriSheinman** [comment]
@jarnedemeulemeester is the issue also fixed in the main app?

**Comment by jarnedemeulemeester** [comment]
Yes it is! 
I found a way to easily convert the language code to full their full display name

**Comment by UriSheinman** [comment]
Awesome! Thank you so much it has been bugging for a while. Will it also display their name if it has one (for stuff like commentary?)
Also also will this update come with android tv or is it planned for earlier/ later?
Again thank you so so much for all the work you do!!

**Comment by jarnedemeulemeester** [comment]
The name of the track is also displayed.
This is the format for now: `<name> - <language> - <codec>`
If the track has no name it will be: `<language> - <codec>`

This change will come together with the Android TV release.
