### ISSUE TITLE
Playing other content doesn't pause findroid playback

### ISSUE THREAD

**Issue by UriSheinman** [jarnedemeulemeester/findroid#536]
**Describe the bug**
If you play any piece of content on findroid, and then try to play music or get a phone call, it wont pause like other players (notably mx since thats the one I use).

**To Reproduce**
1. Play any type of media
2. a. Either play another type of media from a different service (for example start playing a song on spotify or when in PiP play a video on youtube).
b. Answer a phone call
3. See error

**Expected behavior**
As a different audio stream starts to play, pause the findroid stream. 

**Screenshots**

https://github.com/jarnedemeulemeester/findroid/assets/132785427/f13263d0-4a71-4822-9801-4da56f2df325
The video showcases how both the episode and the video play simultaneously (no audio don't worry).

**Device info (please complete the following information):**
 - Device: Nothing Phone 1
 - Android version: 13
 - App version: 0.13.1
 - Jellyfin version: 10.8.11

**Comment by Yash-Garg** [comment]
I'm unable to reproduce this on my 2 devices both running Android 13.

Also, according to Android docs:

> [Android 12 (API level 31) or later](https://developer.android.com/media/optimize/audio-focus#audio-focus-12)
Audio focus is managed by the system. The system forces audio playback from an app to fade out when another app requests audio focus. The system also mutes audio playback when an incoming call is received.

**Comment by UriSheinman** [comment]
But this bug only happens to me with findroid, so the system might not recognize it as media playback? Idk I honestly don't know

**Comment by Yash-Garg** [comment]
Yeah, not sure why it's happening since I am unable to reproduce it.

**Comment by jarnedemeulemeester** [comment]
I was able to reproduce this bug on my Pixel 6 running Android 14 QPR1 Beta 1. 
It seems to only be an issue with the mpv player. The default (ExoPlayer) seems to stop the playback fine when an other app requests audio focus.
I will investigate.

**Comment by jarnedemeulemeester** [comment]
Apparently mpv does not request audio focus.
https://github.com/jarnedemeulemeester/findroid/blob/d65591a19ec3beefc7daaf63ec6811777a41d8d7/player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt#L96

If I enable it, it does work and correctly pauses the playback when an other app requests audio focus.
But when starting the playback again it does not request focus, hence the other app that's playing something continues and it becomes a mess.

I will take a look at fixing it :)

**Comment by Yash-Garg** [comment]
> Apparently mpv does not request audio focus.
> 
> https://github.com/jarnedemeulemeester/findroid/blob/d65591a19ec3beefc7daaf63ec6811777a41d8d7/player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt#L96
> 
> If I enable it, it does work and correctly pauses the playback when an other app requests audio focus. But when starting the playback again it does not request focus, hence the other app that's playing something continues and it becomes a mess.
> 
> I will take a look at fixing it :)

can also check https://github.com/mpv-android/mpv-android/commit/172abaccb70ce257fa92d18ac27f49a0cf7d3823

**Comment by UriSheinman** [comment]
> Apparently mpv does not request audio focus.
> 
> https://github.com/jarnedemeulemeester/findroid/blob/d65591a19ec3beefc7daaf63ec6811777a41d8d7/player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt#L96
> 
> If I enable it, it does work and correctly pauses the playback when an other app requests audio focus. But when starting the playback again it does not request focus, hence the other app that's playing something continues and it becomes a mess.
> 
> I will take a look at fixing it :)

Any update @jarnedemeulemeester ?
