### ISSUE TITLE
Can't see folder

### ISSUE THREAD

**Issue by billouetaudrey** [jarnedemeulemeester/findroid#560]
Hi, I have an other with only folder (not scan by scrapper)

But can see these

Can you help something? 

Thanks

**Comment by GreatestFool** [comment]
I think you first need to elaborate on what the issue actually is.

**Comment by billouetaudrey** [comment]
With other account, I can see my movie
But with one account only folder are added, it's empty
No issue with jellyfin

Here you can see screenshots

https://telegra.ph/Findroid-issue-10-31

Thanks

**Comment by GreatestFool** [comment]
Findroid doesn't support all Library types. It supports Movies and Shows, and does not support Mixed types, from my testing. I haven't tested e.g. a music library or book library, but I suspect those won't work either.

What Library type is yours?

Also, just to make sure I understand correctly. You've tested with the same user but can only see the Library using that user in the first-party Jellyfin app but not in Findroid, correct?

**Comment by billouetaudrey** [comment]
It's video too, just see by one user (Adult)
If I select an other user with my other video, no issue (maybe because they are scan)
And yes, no issue with Jellyfin app, but not on Findroid 👍

**Comment by billouetaudrey** [comment]
Fixed : was filetypes library issue

Sorry
