### ISSUE TITLE
Subtitle issue

### ISSUE THREAD

**Issue by Gottarocket** [jarnedemeulemeester/findroid#57]
**Describe the bug**
 
Either downloaded or subtitle on the media file of movie or show doesnt show on fritter player 

**To Reproduce**
1. Go to video 
2. Click on play
3. Click on subtitle icon select subtitle 
4. No subtitle shows up . 

**Expected behavior**
Subtitle should show on all format of video
**Screenshots**

**Device info (please complete the following information):**
 - Device: [e.g. Google Pixel 3]
 - Android version: [e.g. 12]
 - App version: [e.g. v0.1.1 (2)]

**Additional context**
Not all videos have this issue only few I believe which  need software decoding also new subtitle downloaded doesnt show up from opensubtitle plugins on jellyfin as selection under subtitle

**Comment by nrodriguez300** [comment]
I am also experiencing the same issue with a Samsung s20 running Android 11. Not all videos run into this issue, but a few definitely are not playing the subtitles.

**Comment by Maxplosion** [comment]
could this issue be only with external subtitles? as far as I remember external subs are not yet supported. (I hope they will be soon, as 99% of my files only have external subs)

**Comment by Gottarocket** [comment]
They work fine on jellyfin web end on thier app too but subtitle doesnt show up on this app . Does give options but selecting any one of them doesnt give any results

**Comment by jarnedemeulemeester** [comment]
External subtitles are supported since 0.5.0.
