### ISSUE TITLE
Rokid max

### ISSUE THREAD

**Issue by ignacio82** [jarnedemeulemeester/findroid#581]
Currently findroid is not available on the playstore when using the rokid max. However the jellyfin app is available and works without any problems. Could you make the app available for that device?

**Comment by alexandru0-dev** [comment]
@ignacio82 i think that the Rokid uses Android TV as the operating system, so u will need to wait for the android-tv version to be release as it's not currently released (bc of missing features, screens, etc) but it's being developed. (u can check the android-tv branch)

**Comment by jarnedemeulemeester** [comment]
Findroid should be available once it is released on Android TV devices.

Closing this.
