### ISSUE TITLE
Replace ConfusedPolarBear's intro-skipper with jellyfin-plugin-media-analyzer

### ISSUE THREAD

**Issue by Meyu-Sys** [jarnedemeulemeester/findroid#590]
As the title says.
ConfusedPolarBear has archived [intro-skipper](https://github.com/ConfusedPolarBear/intro-skipper) and active development has ceased replace it with the most prominent fork [jellyfin-plugin-media-analyzer](https://github.com/endrl/jellyfin-plugin-media-analyzer) made by endrl

**Comment by mihawk90** [comment]
IMO that plugin is not just a simple fork. While it relies on the same kind of detection it is an entirely different plugin. CPB's plugin was basically split in 4, it requires (at this time anyway) a patched version of Jellyfin until the media segments API is upstreamed, and it requires jellyfin-vue as a webinterface as well.
This is very much not intended for an enduser currently. It's for people that want to test cool new stuff that may or may not make it into Jellyfin eventually. It requires a lot of steps to even get working.

I agree that findroid should eventually transition to the media segments API, but I'd argue that only makes sense once the API is stable, i.e. in a Jellyfin release.

**Comment by AbandonedCart** [comment]
Have you looked into https://github.com/jumoog/intro-skipper? I know this was posted a little while back, but I only arrived a few days ago.

You do not need a custom web player. All you actually need is ffmpeg with Chromaprint (for now) and I believe Mac is the only one that doesn't include that natively right now. They promised it would be in the next major release, though.

If you are a new user, Jellyfin Media Analyzer may be a bit more robust after you meet all of the requirements (media segments API and Vue player). They are only calling it a fork for the sake of tapping the user base, but the only similarity is the end result.

**Comment by Meyu-Sys** [comment]
Endrl has made a pull request integrating some version of this plugin into the main jellyfin repo.
https://github.com/jellyfin/jellyfin/pull/10530

**Comment by AbandonedCart** [comment]
It's not a version of the plugin, only the API that is needed for Jellyfin Media Analyzer. You would still be missing the EDL creator, Jellyfin Segment Editor, and the actual Jellyfin Media Analyzer after that PR.

**Comment by mihawk90** [comment]
That PR was also already around when this Request was created (which I mentioned in my first reply).

Regardless, even once everything is upstreamed, it would still need work on Finamp to actually work with it, so I'm not sure why you'd close this issue as the original requester.
