### ISSUE TITLE
Library images are too big

### ISSUE THREAD

**Issue by OctoNezd** [jarnedemeulemeester/findroid#6]
It looks like libraries section is designed to fit only about 2 items, but some people have more than 2 libraries to separate languages and other stuff. 
Please add option for different display design or shrink the items?
![image](https://user-images.githubusercontent.com/15308404/130278044-212600d0-dd6f-48e4-a3be-bc20dfa29d9e.png)

**Comment by jarnedemeulemeester** [comment]
I decreased the size of the libraries.
Should be improved with next release!
