### ISSUE TITLE
My Media does not show any media.

### ISSUE THREAD

**Issue by abinlatheef** [jarnedemeulemeester/findroid#607]
**Describe the bug**
The 'My Media' tab does not show any media. Searching works though. Home page shows both 'Continue watching' and 'Next up'.

**To Reproduce**
1. Open the app.
2. Click on 'My Media' tab, the second one at the bottom.
3. Its just blank.

**Expected behavior**
It should show the media on my server. I have different libraries for Movies and TV Shows.

**Screenshots**
![Screenshot_20231231-121618](https://github.com/jarnedemeulemeester/findroid/assets/63762448/be76c6c2-53bd-42fc-90e6-1d927800d74a)

**Device info (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - Android version: 14
 - App version: 0.13.1
 - Jellyfin version: 10.8.0 (jellyfin-git from Arch-AUR)

**Comment by abinlatheef** [comment]
Hi again.
I tried a different version of jellyfin on my PC. Now the issue is fixed. It was the out of date git version that brought the trouble.
Sorry for trouble. And thanks again for a such a great app!

**Comment by writeblankspace** [comment]
Hello, I downloaded the app from F-droid and the same thing happened to me.
