### ISSUE TITLE
Black background behind subtitles randomly

### ISSUE THREAD

**Issue by nathangur** [jarnedemeulemeester/findroid#613]
I've always had no background on my subtitles when watching Findroid. But after I began rewatching a show that had no subtitle background, suddenly I have a big black background behind the subs. I didn't change or touch anything.

**Comment by nathangur** [comment]
Narrowed this down to NOT being on the mpv player and having it enabled.

**Comment by Jcuhfehl** [comment]
Exoplayer uses your system subtitle settings. You can change them from settings>player>subtitles

**Comment by Natanel-Shitrit** [comment]
> Exoplayer uses your system subtitle settings. You can change them from settings>player>subtitles

Yep this is the reason for this behavior, I think this issue can be closed now 😄
