### ISSUE TITLE
Migrate to AndroidX Media3?

### ISSUE THREAD

**Issue by eff3ry** [jarnedemeulemeester/findroid#614]
I saw that the exoplayer repo has been labeled as deprecated and is encouraging people to migrate to AndroidX Media3, I know this will likely be a big refactor. But is this something that is going to happen/Is worth doing?

**Comment by peerless2012** [comment]
Already with media3 in the project .

**Comment by eff3ry** [comment]
I see, my bad, thanks for letting me know!
