### ISSUE TITLE
Doesn't Show anything

### ISSUE THREAD

**Issue by llessi06** [jarnedemeulemeester/findroid#615]
I have my own Jellyfin Server and there are around 800 .flac music files on it, but the app doesn't show them neither in the home screen or when I search for them. In the official Jellyfin App they are shown.
But I want to use your App because it has an offline functionality.

Expected behaviour is that the songs and playlist shows up.

![Screenshot_2024-01-07-16-13-17-076_dev jdtech jellyfin~2](https://github.com/jarnedemeulemeester/findroid/assets/120971197/785e9d4d-d3f3-4b4b-a291-dbaa9d49e109)
![Screenshot_2024-01-07-16-13-54-349_dev jdtech jellyfin-edit](https://github.com/jarnedemeulemeester/findroid/assets/120971197/8b78b766-25dd-4565-afbe-12cfbd319391)

 - Device: Xiaomi Redmi Note 12 Pro
 - Android version: 13
 - App version: 0.13.1
 - Jellyfin version: 10.8.13

**Comment by neopc10** [comment]
Findroid is third-party Android application for Jellyfin that provides a native user interface to browse and play movies and series.

**Comment by llessi06** [comment]
Okay thanks. Then I'll look for another Jellyfin app with support dir music.

**Comment by neopc10** [comment]
Take a look at Symfonium (paid)
