### ISSUE TITLE
Support on skipping credits in intro skipper

### ISSUE THREAD

**Issue by smarttommyau** [jarnedemeulemeester/findroid#620]
**Is your feature request related to a problem? Please describe.**
Credits not able to be skipped

**Describe the solution you'd like**
Avaliable in [https://github.com/jumoog/intro-skipper]()'s build
Use"IntroSkipperSegments"(support both intro and credits) at first and use "IntroTimestamps"(this only support intro)
Format of IntroSkipperSegemets:
```
{
    "Introduction": {
        "EpisodeId": "1e3cf41f1ae051f68ab56980f937f745",
        "Valid": true,
        "IntroStart": 145.792,
        "IntroEnd": 228.497,
        "ShowSkipPromptAt": 140.792,
        "HideSkipPromptAt": 155.792
    },
    "Credits": {
        "EpisodeId": "1e3cf41f1ae051f68ab56980f937f745",
        "Valid": true,
        "IntroStart": 1313.264,
        "IntroEnd": 1408.2640000000001,
        "ShowSkipPromptAt": 1308.264,
        "HideSkipPromptAt": 1323.264
    }
}
```

**Additional context**
This should only introduce some small modification without breaking the original support, hope this can be implemented.

**Comment by Natanel-Shitrit** [comment]
I know it's not exactly what you are asking for but after
- #466

is merged it's possible to create a "generic" way to skip intros / credits sections, without any 3rd party plugins :)

**Comment by AbandonedCart** [comment]
@Natanel-Shitrit Assuming your video supports it, this also eliminates a lengthy scan that requires Chromaprint, but it just doesn't have that "Netflix" feel to it.

**Comment by Natanel-Shitrit** [comment]
> @Natanel-Shitrit Assuming your video supports it, this also eliminates a lengthy scan that requires Chromaprint, but it just doesn't have that "Netflix" feel to it.

Most of the shows that I have (Anime) have chapters, that might not be the case for "normal" shows.

You can integrate the chapters with the skip button if you want the "Netflix" feel - I just suggested to use the chapter info as the way of detection for the intro / credits 😄

**Comment by AbandonedCart** [comment]
It almost begs the question why literally everyone opted for Chromaprint, but not a single static ffmpeg for Mac enables it.

Anyway, that isn't why I was here. I was actually here to mention a bug in the plugin that seems to have translated to a bug in this app. If you skip an intro and the position you land on is still considered "intro" then the button will remain visible. Even worse, clicking on it will take you back to the end of the intro. Keep clicking and you could loop forever.

**Comment by Natanel-Shitrit** [comment]
I guess you are referring to your discussion here https://github.com/jumoog/intro-skipper/issues/52
I saw you said:
> They are determining when the button is displayed on their end. I don't know if there is a check somewhere else, but it's essentially keeping the button visible the entire time the intro is playing.

And you linked this check:
https://github.com/jarnedemeulemeester/findroid/blob/c30b76d4f1e94810b60561c92ab8081fdddc5d44/player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt#L247-L262

Doesn't `showSkipPromptAt` and `hideSkipPromptAt` is given by the plugin?
So if you fixed the `segment.IntroEnd` shouldn't it reflect on `hideSkipPromptAt`?

https://github.com/jumoog/intro-skipper/blob/f49bf50a5b87d470ea387ec1c59b848043a57246/ConfusedPolarBear.Plugin.IntroSkipper/Controllers/SkipIntroController.cs#L89-L102
> GitHub only renders snippets from the origin repo 😢

**Comment by AbandonedCart** [comment]
Actually, no. Two different apps can use the same database, but interpret the values differently. That's what is happening.
