### ISSUE TITLE
Switch support from the confused polarbear original plugin to jumoog fork

### ISSUE THREAD

**Issue by UriSheinman** [jarnedemeulemeester/findroid#632]
**Is your feature request related to a problem? Please describe.**
The confused polar bear plugin has died, and it seems like the jumoog fork is the most advanced fork currently. 

**Describe the solution you'd like**
Supporting all the features added by this fork. 

**Additional context**
For example support for credits and for intro prompt customization.

**Comment by Natanel-Shitrit** [comment]
Duplicate of:
- #620

**Comment by UriSheinman** [comment]
> Duplicate of:
> 
> * [Support on skipping credits in intro skipper #620](https://github.com/jarnedemeulemeester/findroid/issues/620)

Sorry, you're right, closing.
