### ISSUE TITLE
Support paging when loading media items

### ISSUE THREAD

**Issue by lsrom** [jarnedemeulemeester/findroid#64]
Right now we use items API just to get all items matching our specified parameters but that can be hundreds or thousands of items. For example, LibraryFragment can load entire movie collection which might be massive for some users.

Luckily Jellyfin enables us to use `startIndex` and `limit` parameters to specify how much items we want and from what offset. I suggest we use this to load items in smaller batches. 

### Goal

- load items in smaller chunks
- preserve the infinite scrolling / detect when user scrolls close to the end of currently loaded items and load more
- ideally use already existing solution, such as: https://developer.android.com/topic/libraries/architecture/paging/v3-overview

**Comment by Rorschach1010** [comment]
I just installed the new 0.3.0 update and this app is getting fucking awesome. However, I have to +1 this suggestion. I would lie if I would say that I understand what @lsroms solution is as I don't know anything about android development but I have about 800 movies and while I like the new sorting options, you still have to scroll down hundreds of movies. 

So there are two things. 
First, you want to quickly browse through the collection and maybe a bar on the right side showing the Letters of the alphabet isn't such a bad idea. I think the google dialer handles it fine with this solution. 
The second thing is that you want to quickly return to the beginning so an arrow which brings you back up seems a good idea.

As I said, if @lsroms solution is doing that, it would be great and would add a lot to this great app.
