### ISSUE TITLE
Missing Episodes Show Up Twice

### ISSUE THREAD

**Issue by Dan6erbond** [jarnedemeulemeester/findroid#647]
**Describe the bug**

I'm using the Jellyfin TVDB plugin that supports showing missing episodes in shows, which I believe creates dual entries in the API for the missing episodes when it's actually available. 

Findroid ends up showing both. While playing works fine, it's a bit of an annoyance. 

**To Reproduce**

1. Install Jellyfin TVDB plugin
2. Enable "Missing Episodes Fetcher" Metadata Downloader in TV show library

**Expected behavior**

Findroid should perform the same checks Jellyfin's native apps do to ignore missing episodes that aren't actually missing. 

**Screenshots**

![Screenshot_20240202_130102_Findroid.jpg](https://github.com/jarnedemeulemeester/findroid/assets/32235074/f08cdea4-90a7-481f-9a89-2225b66656b8)

**Device info (please complete the following information):**
 - Device: Samsung Galaxy S23
 - Android version: 14
 - App version: 0.13.1 (22)
 - Jellyfin version: 10.8.13

**Additional context**

Let me know if an API request for the show with the missing episodes could help.

**Comment by jarnedemeulemeester** [comment]
I cannot reproduce this. 
Enabling TheTVDB plugin and Missing episodes fetcher does not create missing episodes entries for episodes that are present.
This seems more like an issue with Jellyfin https://github.com/jellyfin/jellyfin/issues/7207
And besides, I don't think Findroid should do extra work filtering the API response. It should be Jellyfin that replies correctly.

You may still send an API request / reply. But I don't think I will add the extra filtering required to remove duplicates.
