### ISSUE TITLE
Unable to log in to the server. Unknown error

### ISSUE THREAD

**Issue by Nioctris** [jarnedemeulemeester/findroid#668]
**Describe the bug**
The app detects my Jellyfin server, but after connecting, when logins and password are required, I enter them, but authorization doesn't happen. The application reports that an unknown error has occurred. On the Jellyfin server itself, I see that the authorization was successful, and the device is authorized. My main system is Linux and the Jellyfin server runs on it, but if I install Jellyfin on Windows on the same pc, there is no such problem. 

**To Reproduce**
1. I don't know

**Expected behavior**
Authorization should be successful

**Screenshots**
![photo_2024-02-20_20-25-00](https://github.com/jarnedemeulemeester/findroid/assets/61637115/f4b76aef-e361-4363-b8fd-b15ef33bfd0d)

**Device info (please complete the following information):**
 - Device: Lenovo Legion Y700, Redmi Note 9 Pro, Poco F4
 - Android version: 12, 13
 - App version: 0.13.1
 - Jellyfin version: 10.9.0

**Additional context**
Other Jellyfin clients authorize without problems, such as Switchfin and Official Android client

**Comment by Nioctris** [comment]
On the stable release of Jellyfin 10.8.13 this problem is not present

**Comment by niravjdn** [comment]
It's still happening on Jellyfin stable version 10.9.11

**Comment by AkashRajpurohit** [comment]
Opened a new issue for this #877
