### ISSUE TITLE
Anime (movies and TV library) not showing up

### ISSUE THREAD

**Issue by YamiYukiSenpai** [jarnedemeulemeester/findroid#669]
**Describe the bug**
I have a media library that's a hybrid of movies and TV shows for all of my anime.  While I can resume them, they don't appear on the list of media.

**To Reproduce**
1. Create a movies and TV show media library

**Expected behavior**
Just like my movies library and my TV show library, my anime library should be accessible and list my anime.

**Screenshots**
Findroid
![Screenshot_20240222_082125_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/13153124/25f79f08-4df9-4c77-b2e9-0ee6cc92c967)
![Screenshot_20240222_082129_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/13153124/b3bb80a2-1a8f-4ec3-9792-4b9477c83747)

Jellyfin
![Screenshot_20240222_110514_Jellyfin](https://github.com/jarnedemeulemeester/findroid/assets/13153124/cf626c30-7df8-4410-861c-05fdd3a2538a)

**Device info (please complete the following information):**
 - Device: Samsung Galaxy Z Flip 4
 - Android version: 14
 - App version: 0.13.1
 - Jellyfin version: 10.8.13

**Additional context**

**Comment by SinTan1729** [comment]
A similar thing is happening to me as well. For me, the anime does show up, but there are no episodes when I open it. Also, this isn't happening for all anime, just a few. Frieren is one example where it's happening.

**Comment by Natanel-Shitrit** [comment]
That's because you set your library type to `other` ("Mixed") - Findroid currently support only `Shows` and `Movies`.

There is a PR open for mixed library support:
- #628

Also - there are a lot of other issues opened for this topic:
- #224 
- #154 
- #352 
- #497

**Comment by Natanel-Shitrit** [comment]
> A similar thing is happening to me as well. For me, the anime does show up, but there are no episodes when I open it. Also, this isn't happening for all anime, just a few. Frieren is one example where it's happening.

This doesn't sound like a similar issue - If I had to guess your library is just not synced automatically when media is imported and Jellyfin doesn't know your media is in the library.

Please open a separate issue if you want help :)

**Comment by SinTan1729** [comment]
> If I had to guess your library is just not synced automatically when media is imported and Jellyfin doesn't know your media is in the library.

That's not the case. Everything appears correctly in the official app. I'll open an issue.
