### ISSUE TITLE
The AMOLED dark theme is not applied to the navbar and Dynamic colors not working on the latest v2024.02.

### ISSUE THREAD

**Issue by ccrsxx** [jarnedemeulemeester/findroid#673]
**Describe the bug**
The AMOLED dark theme is not being applied to the navbar, and dynamic colors are not functioning as expected in the latest version v2024.02.

**To Reproduce**
1. Navigate to `Settings > Appearance`
2. Enable both `Dynamic colors` and `AMOLED dark theme`
3. Return to the homepage
4. See the navbar still has a default grayish color, and dynamic colors continue to use the default color.

**Expected behavior**
The navbar should have a black background color and dynamic colors should be applied, similar to the behavior in the previous version.

**Screenshots** 
| Bugged version v2024.02 | Working version v0.13.1 |
| ------------------------------- | ------------------------------ |
|![Screenshot_20240229_163547_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/55032197/f366bfc9-5711-49bc-9661-ce87fb272e71)|![Screenshot_20240229_164052_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/55032197/a7822ba1-12cd-490e-aa88-fa2d1d193597)|

**Device info:**
 - Device: Samsung Galaxy S23+
 - Android version: 14
 - App version: v2024.02
 - Jellyfin version: 10.8.10

**Additional context**
I’ve tried clearing the app data and reinstalling it, but the issue persists. Currently, I’m using the previous version v0.13.1, where everything works correctly.

**Comment by Natanel-Shitrit** [comment]
Thanks for the detailed issue, I found a solution - will open a PR soon.
