### ISSUE TITLE
Finished Dutch translation

### ISSUE THREAD

**Issue by Iliannnn** [jarnedemeulemeester/findroid#674]
Finished Dutch translation: https://weblate.jdtech.dev/projects/findroid/-/nl/

**Comment by Natanel-Shitrit** [comment]
Thanks for the contribution!
Translation are committed automatically - there is no need for an issue 😄

**Comment by Iliannnn** [comment]
Didn't know. Great work with this project! Hope downloading whole episodes may come soon. Best of luck!
