### ISSUE TITLE
Episodes not showing up

### ISSUE THREAD

**Issue by 666Anon** [jarnedemeulemeester/findroid#675]
**Describe the bug**
Some episodes are not showing up in Findroid. Findroid shows that there's something, since the season has the small 1 on top. But it's empty when I open it. They show up fine in the official app. I haven't noticed this for any movies. Also, this doesn't happen for every show, but when it does happens it seems to keep happening for that particular show. It gets fixed if I run `Refresh metadata` on that episode.

**To Reproduce**
1. Open the show in question.
2. Go to the latest season.
3. It's empty.

**Expected behavior**
The episode(s) should be there.

**Screenshots**
![Screenshot_20240301_105602_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/115513169/9fd34793-e718-43f6-a16d-33a6985bf2db)
![Screenshot_2240301_105607_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/115513169/2047f69c-a762-4105-a517-0e3ad03e3c36)

**Device info (please complete the following information):**
 - Device: Samsung Galaxy S22
 - Android version: 14
 - App version: 2024.02
 - Jellyfin version: 10.8.13

**Additional context**
The location for that file in question is `/download/Anime/Frieren/Frieren - Beyond Journey's End - S01E25 - A Fatal Vulnerability - WEBDL-1080p.mkv`.

**Comment by Natanel-Shitrit** [comment]
Do you have upgrades configured?
My guess is that the file got replaced and Jellyfin didn't scan the new file yet. (that's why the rescan fixed it)
But what's weird here is that the whole series is gone.

I can try and debug this if your Jellyfin instance is public and you are willing to let me have a test user 😄

**Comment by 666Anon** [comment]
> My guess is that the file got replaced and Jellyfin didn't scan the new file yet.

Don't think that's the case. As I mentioned, it works in the official app.

> I can try and debug this if your Jellyfin instance is public and you are willing to let me have a test user

That's fine by me. How can I give you the creds privately?

**Comment by Natanel-Shitrit** [comment]
> > My guess is that the file got replaced and Jellyfin didn't scan the new file yet.
> 
> Don't think that's the case. As I mentioned, it works in the official app.
> 
> > I can try and debug this if your Jellyfin instance is public and you are willing to let me have a test user
> 
> That's fine by me. How can I give you the login details privately?

You can find me in the [Findroid Discord](https://discord.gg/tg5VvTFwTV)
![image](https://github.com/jarnedemeulemeester/findroid/assets/65548905/5c8f2896-ad42-4c93-b961-2d4e04ee5457)
Or just add me: `luqs`

I'll only be able to check this out over the weekend, so no rush 🙂

**Comment by Natanel-Shitrit** [comment]
Okay we pretty much narrowed it to Jellyfin labeling stuff with `unknown season` because Sonnar wasn't configured with season directories.

@666Anon enabled season directories and we'll see if that fixes the problem 😄

**Comment by 666Anon** [comment]
After a week or so of usage, looks like that was the fix indeed. Thanks @Natanel-Shitrit for helping me figure it out.
