### ISSUE TITLE
Add user failed when different server with same user.

### ISSUE THREAD

**Issue by peerless2012** [jarnedemeulemeester/findroid#677]
I have two different jellyfin server with different ip address, and they both have the same user (name and psw), when I add second address and login, the login is fail and have unknown error.

I clone the code and debug, i find that the server is not insert to the database and when insert second user,  the user have a foreign key error.

**Device info (please complete the following information):**
 - Device: Google Pixel 5
 - Android version:14
 - App version: 2024.02
 - Jellyfin version: 10.8.12

**Comment by jarnedemeulemeester** [comment]
Do your servers have the same id? 
You can find the id of your server at `http://<ip_address>:<port>/system/info/public`

**Comment by peerless2012** [comment]
The server id is the only key to identify a server, these two different servers, must have different server id.

**Comment by Natanel-Shitrit** [comment]
I'm pretty sure you can't add a different server as another address - I'm not sure but it probably uses a token for authenticating and it's different across different servers.

**Comment by peerless2012** [comment]
Yes, that's what happend on me, I have two different jellyfin server, but the account is the same.

**Comment by jarnedemeulemeester** [comment]
You must add the second server as a separate server. You cannot add the address of the second server to the first server in Findroid. That does not make any sense.
In Findroid, go to Settings -> Server -> Add server

**Comment by peerless2012** [comment]
> You must add the second server as a separate server. You cannot add the address of the second server to the first server in Findroid. That does not make any sense. In Findroid, go to Settings -> Server -> Add server

That's the way, I didn't mention the server options before. Thanks a lot for you.
