### ISSUE TITLE
Unknown error when trying to Login

### ISSUE THREAD

**Issue by K-Anudeep** [jarnedemeulemeester/findroid#679]
**Describe the bug**
I have updated my Jellyfin server to 10.9 and I have issue logging into it with Findroid. I can see on the Dashboard activity that Findroid is detected and Authentication is successful but Findroid is stuck on the Unknown error page.

**To Reproduce**
1. Have Jellyfin version 10.9.0
2. Login via Findroid

**Expected behavior**
Findroid to open Jellyfin Libraries

**Screenshots**
![image](https://github.com/jarnedemeulemeester/findroid/assets/40020533/9980ed31-f3d4-4c50-96d7-1e9b796ee80a)

![image](https://github.com/jarnedemeulemeester/findroid/assets/40020533/fff08133-f348-422e-84cc-2c5b26fcf8fb)

**Device info (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Android version: 12
 - App version: 2024.02
 - Jellyfin version: 10.9.0

**Comment by jarnedemeulemeester** [comment]
Findroid only officially supports the latest stable Jellyfin version (10.8.13 at the time of writing)
Jellyfin 10.9 still unstable and not released yet.

Also, the error you are encountering is inside the Kotlin SDK provided by the Jellyfin team so I can't easily fix it right now even if I wanted to.

**Comment by niravjdn** [comment]
Is it still same case where findroid only supports jellyfin version up to 10.8?
