### ISSUE TITLE
Bug(player): player close itself if play ISO

### ISSUE THREAD

**Issue by boydaihungst** [jarnedemeulemeester/findroid#680]
**Describe the bug**
The player crashed itself if played ISO. I tested in both Findroid and Jellyfin's official app. On the official app, it works but I can't fast-forward. On findroid I can't play at all, the player crashed after buffering.

**To Reproduce**
1. Open findroid 
2. Go to any movie which is an ISO file
3. Click play
4. The player crashed

**Expected behavior**
The player should play ISO without error.

**Screenshots**
![Screenshot_20240305-065734_Firefox_Nightly](https://github.com/jarnedemeulemeester/findroid/assets/38396158/dfe9920a-63d8-4ae4-a0e2-c598251507ed)

Video
https://github.com/jarnedemeulemeester/findroid/assets/38396158/b65201bc-4e3f-453d-9c9c-365bb92e0603
**Device info (please complete the following information):**
 - Device: Nubia Red magic 6s pro
 - Android version: 14
 - App version: 2024.02 (23)
 - Jellyfin version: 10.8.13

**Additional context**

**Comment by UriSheinman** [comment]
I think it's both a jellyfin main problem (they don't really play well with isos) and a findroid problem (as I'm pretty sure non of the players support it from what I can find).
Correct me if I'm wrong cause I just use mkvs...
