### ISSUE TITLE
Update versioning confuses Obtainium

### ISSUE THREAD

**Issue by githupper** [jarnedemeulemeester/findroid#681]
**Is your feature request related to a problem? Please describe.**

Obtainium is showing as '2024.02" version installed with an available update v0.14.02 as Latest. Even after updating, it's still showing as Update available in Obtainium. This problem is unique to Findroid only for a long while and what I did to circumvent it previously was installation via FDroid Izzydroid repo previously and not Obtainium.

Would like to check if there is any way to fix it as Findroid is not available in Izzydroid now.

**Describe the solution you'd like**
I understand there are expressions function in Findroid that may fix this but I am not fluent in fixing this problem using expressions. If this can work, can advise what is the current expression to use?

Thank you for your time in reading this and developing Findroid!

**Comment by Jcuhfehl** [comment]
Findroid is still in the izzydroid repo, and this seems like an obtanium issue. Obtanium should prioritize the version with the higher versioncode which is always newer than one with a lower versioncode. You should probably open an issue on obtanium's github

**Comment by jarnedemeulemeester** [comment]
I changed the versioning back to SemVer. Maybe that's why Obtainium is confused.
The current 2024.02 is now known as 0.14.0 (even tho the version inside the apk still says 2024.02).

I will release v0.14.1 soon with some bug fixes. Hopefully this fixes the Obtainium issue.

**Comment by NicholasFlamy** [comment]
Either versioning should work perfectly with Obtainium (I use Obtainium and helped with testing and finding bugs and am planning to assist in writing a lot more documentation.)

The problem is likely due to inconsistency.

Now that the version code on GitHub was changed back, but the apk has the newer veraioning, it's absolutely going to break Obtainium Version detection but it should fall back to pseudo-version.

@jarnedemeulemeester I might fork Findroid and copy release 0.13.1 and release 0.14.0 and publish them on my fork to test this, I'll of course rename 0.14.0 back to the new versioning (making it "2024.02") to see Obtainium behavior. I'm pretty sure it can handle this correctly.

**Comment by NicholasFlamy** [comment]
I should add, I'm not currently using Obtainium to install Findroid because I had Findroid installed from Google Play a year or two maybe more ago. Before Obtainium existed I think. So that is why I was not able to test the new versioning at release.

**Comment by NicholasFlamy** [comment]
With default config in Obtainium it works fine on this repo:
https://github.com/NicholasFlamy/findroid

**Comment by NicholasFlamy** [comment]
Note: I still have the Google Play Version installed.

![Screenshot_20240305_155757](https://github.com/jarnedemeulemeester/findroid/assets/30300649/0be721ff-bc41-4138-946e-b0aeb3e4d713)
![Screenshot_20240305_155746](https://github.com/jarnedemeulemeester/findroid/assets/30300649/c211466f-40ff-410f-8356-8bb197c8ded2)

**Comment by NicholasFlamy** [comment]
FYI, for version on GitHub, Obtainium uses the tag, so whatever you do, keep the tag and app version the same, or at least similar, if one has a v and the other doesn't Obtainium can automatically handle that I think. I also know that if they're similar enough adding a little RegEx in Obtainium will take care of it.

**Comment by jarnedemeulemeester** [comment]
Yeah I will keep the git tag and the in app versions the same.
I renamed v2024.02 to v0.14.0 for consistency. 
New release (v0.14.1) incoming which should fix this...

**Comment by NicholasFlamy** [comment]
@githupper would you happen to have a screenshot of the issue (now it'll be bugged until 0.14.1 so not rn) when it happened? I'm just curious to investigate this. Also, I would kinda like to see your Obtainium settings for Findroid.

**Comment by NicholasFlamy** [comment]
I'm 99% sure that's caused by reverting the versioning (not sure of the timeline of events, at first I thought the versioning change was reverted because of this issue but I think it was reverted before this issue.) So now that the new version (0.14.1) is versioned correct it should be fine.
