### ISSUE TITLE
Sincerely hope to develop a version for television as soon as possible.

### ISSUE THREAD

**Issue by brilliantfeat** [jarnedemeulemeester/findroid#693]
Sincerely hope to develop a version for television as soon as possible，Just like Vidhub on Apple TV, it can easily play video witch on the Jellyfin server direct，instead of requiring the server to decode for the client.

**Comment by peerless2012** [comment]
There already have a tv client, but not published, see [tv](https://github.com/jarnedemeulemeester/findroid/tree/main/app/tv) folder in this project.

**Comment by Natanel-Shitrit** [comment]
Hey 😄 
Like @peerless2012 said, the TV version has already been merged, but yet to be released.
It was tracked in the following issue:
- #23

To help us focus on the app development, please check for existing issues before opening a new issue,
Thank you!

**Comment by drizzt09** [comment]
Do we have a estimated  timeframe of it being released?

**Comment by jarnedemeulemeester** [comment]
I understand that people want the TV version as soon as possible.
At this moment there is still some work to be done. Missing features, bugs, etc...

Please do not open issues asking for it to be released.
It will be released when it's ready.
