### ISSUE TITLE
External subtitles support

### ISSUE THREAD

**Issue by gauth-fr** [jarnedemeulemeester/findroid#7]
First thanks for this new app!

It seems external subtitles are not supported, it would be a great addition!

Thanks!

**Comment by jarnedemeulemeester** [comment]
Yes indeed, I agree!

Will add support for external subtitles some time in the future.

**Comment by xsm1997** [comment]
> Second this! Download external subtitles are really easy and you didn't need to remux the original media file.

Does the app have the ability to download external subtitles? Or where should I put the subtitle files when downloaded to get them loaded into the default player?
