### ISSUE TITLE
Screen lock

### ISSUE THREAD

**Issue by damomato** [jarnedemeulemeester/findroid#70]
First of all, great job with the app!

It would be nice to be able to lock the screen the exact same way as the Netflix Android app.

Hopefully not something too troublesome to implement. Sometimes my kid watches videos on my phone but not being able to lock the screen can cause problems.

**Comment by damomato** [comment]
Hi, just wanted to bring this up again

**Comment by jarnedemeulemeester** [comment]
Sorry for the late response.
Just to confirm that this is something I want to add in the future.
When exactly I will add this I can't say, but it is planned!

**Comment by damomato** [comment]
Great to hear, thanks!

**Comment by damomato** [comment]
Good to see thanks :)
