### ISSUE TITLE
Library image not rendering font correctly in SVG

### ISSUE THREAD

**Issue by i8x3** [jarnedemeulemeester/findroid#709]
**Describe the bug**
In Jellyfin, I have library images which are SVGs which require a specific font on the system. I have embedded the font into the SVG if the system does not have the font. This works where I don't have the font (like the mobile version of Jellyfin), but does not work in Findroid.

**To Reproduce**
1. Get an SVG which requires a specific font, but has the font embedded in the SVG.
2. Upload it to a library in Jellyfin, making it the primary image.
3. Save changes.
4. Go onto Findroid, which will show a "default font" (in my case a default Serif font)

**Expected behavior**
For the SVG to show the font which I have specified.

**Screenshots**
![Screenshot_20240328-184642_Jellyfin](https://github.com/jarnedemeulemeester/findroid/assets/102768696/f80a7e33-e8cd-4a86-9b9b-242de2bb9c17)
Without the embedded font, in the Jellyfin Mobile app

![Screenshot_20240328-184706_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/102768696/3b393633-d9ac-4fdf-b90c-ec4df0d8a783)
Without the embedded font, in the Findroid app

![Screenshot_20240328-184207_Jellyfin](https://github.com/jarnedemeulemeester/findroid/assets/102768696/4fdd5e21-05f6-48e8-934a-7aafc20e7cb6)
With the embedded font, in the Jellyfin Mobile app

![Screenshot_20240328-184515_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/102768696/6b870e63-3e8c-404e-9685-8a838b4dd61e)
With the embedded font, in the Findroid app

**Device info (please complete the following information):**
 - Device: Samsung S9+
 - Android version: 10
 - App version: 0.14.1 (24)
 - Jellyfin version: 10.8.13

**Additional context**
Here are the files which I used:
![Primary Movies - no embedded font](https://github.com/jarnedemeulemeester/findroid/assets/102768696/d13634e2-297b-4104-8a9b-01590f02f6e7)
![Primary Shows - no embedded font](https://github.com/jarnedemeulemeester/findroid/assets/102768696/399754eb-8c72-4a6b-9132-e11c0d78e659)
![Primary Shows](https://github.com/jarnedemeulemeester/findroid/assets/102768696/a9f3ae8e-626b-4581-bd7b-1e9b3adc75a0)
![Primary Movies](https://github.com/jarnedemeulemeester/findroid/assets/102768696/886c06fc-ec84-48a5-94a9-250db09632a6)
(ignore the preview when you open it in browser, just save the svg and then view it)

**Comment by jarnedemeulemeester** [comment]
Yeah, I suggest you just convert the text into a Path so that it's not depended on having a specific font installed
