### ISSUE TITLE
Support 10.9 trickplay

### ISSUE THREAD

**Issue by enter-a-random-username** [jarnedemeulemeester/findroid#718]
**Is your feature request related to a problem? Please describe.**
Support Trickplay in 10.9.
 Jellyscrub will be removed and v2 is only a converter from bif to tiled images. Amount of tiles per image can be configured

**Describe the solution you'd like**
Same as before for new format

**Additional context**
10.9 will be stable soon according to the blog.
https://jellyfin.org/posts/testing-10.9.0

**Comment by jarnedemeulemeester** [comment]
Yeah I would love to move to the native trickplay format in 10.9.
But for now we have to wait until the Jellyfin team releases an Kotlin SDK update with the new trickplay properties.
I suspect this will be released around or slightly before the 10.9 release.

**Comment by UriSheinman** [comment]
Is this currently being worked on?

**Comment by jarnedemeulemeester** [comment]
Not at the moment.
However, I am working on a bigger update for Findroid and this will include the new trickplay from 10.9.
