### ISSUE TITLE
Unable to delete downloaded file if media was changed (or removed?) from server

### ISSUE THREAD

**Issue by Goblinlordx** [jarnedemeulemeester/findroid#733]
**Describe the bug**
If I download a file of some media, then at a later time on the server, the file is updated/changed/removed I am then unable to delete the downloaded file. When going to downloads, it appears there but then shows "Invalid HTTP status in response: 500". I suspect it is simply because it will not display information about the episode unless it is able to retrieve details via the same URL which the media was at previously.

**To Reproduce**
1. Go to 'any media'
2. Click on 'download'
3. Change or remove the media from the server.
4. Go to downloaded media area
5. Go to the specific media which was previously downloaded
6. Unable to delete download (or play).

**Expected behavior**
Best case scenario, it might be nice to be able to still play the media regardless of any server response. Worst case scenario, I would expect to, at a minimum, be able to delete the downloaded media.

**Screenshots**

**Device info (please complete the following information):**
 - Device: Google Pixel 6
 - Android version: [14
 - App version: 0.14.2 (25)
 - Jellyfin version: 10.8.13

**Additional context**

**Comment by Natanel-Shitrit** [comment]
A workaround for now is to enter offline mode and you will be able to delete the media.

**Comment by Goblinlordx** [comment]
> A workaround for now is to enter offline mode and you will be able to delete the media.

Hmmm.. that works. Considering that, I just think it should be called out that it is possible. Anyways, I am satisfied with that for now. I will just close 👍

**Comment by Natanel-Shitrit** [comment]
It is a real problem, it would be great if you can keep this open so we can keep track of bugs and fix that eventually 🙂
