### ISSUE TITLE
Add more ABIs to F-Droid/IzzyOnDroid

### ISSUE THREAD

**Issue by sdaqo** [jarnedemeulemeester/findroid#745]
**Is your feature request related to a problem? Please describe.**
The armebi version that is on the izzyondroid repo is incompatible with my device.

**Describe the solution you'd like**
Add the other ABIs (arm, libre) that are also featured in the github releases to the izzyondroid repo.

**Additional context**
My device is a pixel 7

**Comment by sdaqo** [comment]
Thanks to my infinite wisdom I did not check the other issues first, it seems you are planing a release to the offical fdroid repos? You may close this, but having the other abis would still be cool for the meantime!

**Comment by jarnedemeulemeester** [comment]
It's not possible to distribute the other ABIs on IzzyOnDroid as we are already at the maximum size an app is allowed to be on IzzyOnDroid, which is 30MB. Actually Findroid (armv7) is already around 33MB but the owner made an exception.

I am indeed also working on releasing Findroid on F-droid. I'm a bit stuck at the moment but I'll get there eventually.
I'll be pushing for the arm64 version on F-droid (I think only one APK is allowed)

**Comment by sdaqo** [comment]
Alright makes sense, thank you!
