### ISSUE TITLE
Invalid Http status error in homepage. 

### ISSUE THREAD

**Issue by Sarin-jacob** [jarnedemeulemeester/findroid#747]
**Describe the bug**
When home, favorite, search tabs are opened it shows error. But media tab is accessible, and can play content by navigating from media tab. The jellyfin web is working as it is supposed to, official app is working too. 
Error:
```
Invalid HTTP status in response: 500
 G5.c: Invalid HTTP status in response: 500
	at F5.g.d(Unknown Source:517)
	at F5.f.q(Unknown Source:17)
	at C4.a.l(Unknown Source:8)
	at Y4.N.run(Unknown Source:112)
	at m.j.run(Unknown Source:12)
	at e5.m.run(Unknown Source:2)
	at e5.a.run(Unknown Source:97)
```

**To Reproduce**
1. Open findroid app (homepage) 
2. See error
3. Go to search and enter
5. Go to media tab
6. App works without any error

**Expected behavior**
Homepage can be seen

**Screenshots**
![Screenshot_2024-05-10-21-01-01-974_dev.jdtech.jellyfin.png](https://github.com/jarnedemeulemeester/findroid/assets/53591235/404ac4ea-93e8-49be-9b25-f95b32d9fa26)

![Screenshot_2024-05-10-21-00-39-693_dev.jdtech.jellyfin.png](https://github.com/jarnedemeulemeester/findroid/assets/53591235/e87b5c33-8025-4747-92cd-7b899b89569b)

![Screenshot_2024-05-10-21-01-53-876_dev.jdtech.jellyfin.png](https://github.com/jarnedemeulemeester/findroid/assets/53591235/65bfa7e6-a8a1-43e2-934d-e557b25b3015)

**Device info:**
 - Device: Poco F4
 - Android version: 13
 - App version:  v0.14.2
 - Jellyfin version: 10.8.13

Not sure if its problem of jellyfin, but had restarted the jellyfin container and the when checked jellyfin logs I found some errors, don't know if its related.

**Comment by MarkusTieger** [comment]
Does it work with the browser? At least for me, it seems like it is an issue with your jellyfin server.

**Comment by Sarin-jacob** [comment]
Yes it worked in browser, bt my jellyfin instance had some issues. The library database was corrupted, n there were issue with scanning and displaying images in one section of the home page.

I had a earlier backup which had the same corrupted library. Bt findroid showed the home screen properly.

So it might have been some other issue of my jellyfin instance that caused the issue.  But somehow the official app and in the browser, the homepage was shown properly, search functional.

**Comment by leekleak** [comment]
Well http error 500 means "Internal Server Error" so It's _probably_ not findroid's fault.

**Comment by Sarin-jacob** [comment]
Should I close the issue? It seems to be caused by a unique state of corrupted library. The chance of this occurring to someone else dosent seem to be much.
Even though Im curious about why it reacted like that, its better to put in energy making this awesome app even better.

If someone else is curious I can put the corrupted library.db file somewhere. (Is there any security issue I should be know, before putting the library.db file in public? )

Thank you @MarkusTieger @leekleak for helping me. :)

Sidenote: Is it possible to add lazyloading to findroid? I will go through issues, n feature requests to see any are there, else I will create one.

**Comment by jarnedemeulemeester** [comment]
Closing since the issue seems to have been a corrupt library database on the Jellyfin server.
