### ISSUE TITLE
Download Restriction

### ISSUE THREAD

**Issue by nikkoentena** [jarnedemeulemeester/findroid#75]
Currently,  app is ignoring "Allow media downloads" option from the jellyfin server. it let all users download media.

**Comment by nikkoentena** [comment]
@jarnedemeulemeester Thanks for the update. I've tried the latest ver. sadly,  download button still shows up for all users.

**Comment by jarnedemeulemeester** [comment]
Dammit, I just checked the code and I forgot to hide the download button by default on the episode sheet.
Just to verify, is the download button only visible for episodes when you have downloads disabled? It should be gone for movies.

**Comment by nikkoentena** [comment]
ah yes, I can confirm. download button only show up for episodes. It's gone for movies.
