### ISSUE TITLE
Add an option for storing downloaded movies in mulitple files

### ISSUE THREAD

**Issue by MarkusTieger** [jarnedemeulemeester/findroid#752]
**Is your feature request related to a problem? Please describe.**
If you are using a Filesystem on your external sd card with a 4 GB File size limit like FAT32, then you can't download any movies to it, as the file is almost always too big.

**Describe the solution you'd like**
Add an option in the settings to split movies into multiple files

**Describe alternatives you've considered**
None

**Additional context**
Formatting my sd card to exFAT (or any other filesystem without this limit) isn't an option for me, as I am sharing my sd card with my New Nintendo 3DS XL, which requires FAT32.

I will probably make a pull request myself, this issue is only to collect some feedback. (And I don't have time this week anyway)

**Comment by Natanel-Shitrit** [comment]
If you found a solution to your problem it's best to share it.

That's so when someone else has the same problem as you he would be able to use the solution you found 🙂

**Comment by MarkusTieger** [comment]
I don't think it would be a suitable solution for most of the people, but ok.

I coded a software (not public yet, way too many bugs) which injects itself into Android (requires root permissions) and acts like a layer between my sd card and any android app that accesses it. This layer splits any file into multiple parts, if it's created in this folder: "Android/data/dev.jdtech.jellyfin/". Any android app will only see it as one file, but it is stored as multiple.
