### ISSUE TITLE
findriod can't connect to Ipv6 servers 

### ISSUE THREAD

**Issue by SmearyThrower** [jarnedemeulemeester/findroid#753]
![Screenshot_20240521_004403_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/93036561/8d515931-f288-4c68-b031-9d56e7486d3a)

**Comment by jarnedemeulemeester** [comment]
@SmearyThrower you are missing a `:` before the port number

**Comment by SmearyThrower** [comment]
mb
