### ISSUE TITLE
Crash when double tapping elements that initiate navigation

### ISSUE THREAD

**Issue by SmearyThrower** [jarnedemeulemeester/findroid#758]
**Describe the bug**
occasionally findriod crashes while leaving the app

**To Reproduce**
play a video then exit to the main menu

**Screenshots**

https://github.com/jarnedemeulemeester/findroid/assets/93036561/833f3f93-db83-4393-a844-4a915dfc6510

**Device info (please complete the following information):**
 - Device: [A53]
 - Android version: [14]
 - App version: [0.14.2]
 - Jellyfin version: [10.9.2]

**Additional context**
I'm using mpv player

**Comment by SmearyThrower** [comment]
More info: after a bit of testing I noticed findriod crashes when ui elements are double tapped 

![Screenshot_20240529_154552_Device care](https://github.com/jarnedemeulemeester/findroid/assets/93036561/9547406e-1317-440b-b406-75249a811470)

**Comment by Natanel-Shitrit** [comment]
Is it a debug build?

**Comment by Natanel-Shitrit** [comment]
Please test [this build](https://github.com/jarnedemeulemeester/findroid/actions/runs/9310132063?pr=767) and tell me if you can reproduce the bug again :D

**Comment by SmearyThrower** [comment]
> Please test [this build](https://github.com/jarnedemeulemeester/findroid/actions/runs/9310132063?pr=767) and tell me if you can reproduce the bug again :D

yeah that fixs but the UI is a bit sluggish not sure tho if that's cuz it's a debug build

**Comment by Natanel-Shitrit** [comment]
Yes, it's the debug build. 
As long as this doesn't crash it's fine

**Comment by jarnedemeulemeester** [comment]
Renamed this issue to focus on the double tapping issue.
The crash when leaving the player is a seperate issue with mpv.
