### ISSUE TITLE
[BUG] Purple screen when playing videos

### ISSUE THREAD

**Issue by sunnyd24** [jarnedemeulemeester/findroid#765]
**Describe the bug**
When playing some videos, after 14 to 19 minutes of playback the screen turns purple. 
I can stop playback back to UI and restart the playback to get back good video. 
My device is Samsung Galaxy S24 Ultra. 

**To Reproduce**
1. Set settings as per screenshot below, mpv player, HW acc to mediacodec, video output to gpu-next, and audio output to opensles. 
2. Play any video and wait until after 14 to 19 mins
3. Error is shown when video screen turns full purple, I and no error message. 
4. To resolve issue, you have to exit full screen video, back to UI and re-start video playback. 

**Expected behavior**
Video playback good all the time with no fullscreen purple screen. 

**Screenshots**
![Screenshot_20240529_074025_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/46629122/ef8dc608-91e8-4f7d-b936-1f8d3278e81a)
![Screenshot_20240528_234820_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/46629122/10b8ff63-b7d1-4eb0-9136-b70e9e720d3f)
![Screenshot_20240528_201224_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/46629122/b2e2f47d-ffc8-45ea-b107-f08d3f709584)
![Screenshot_20240527_114210_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/46629122/5abc619b-82ac-430b-b881-42d56ddf1742)
![Screenshot_20240526_134117_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/46629122/53615c58-f5e8-4e18-a79c-ac23fe759e86)
![Screenshot_20240526_122734_Findroid](https://github.com/jarnedemeulemeester/findroid/assets/46629122/b195f96c-25f8-40f5-85c4-9817f52e80bc)

**Device info (please complete the following information):**
 - Device: Samsung Galaxy S24 Ultra 
 - Android version: 14 (OneUI 6.1)
 - App version: v0.14.2
 - Jellyfin version: 10.9.2

**Additional context**
Only occurs on some videos, some playback fine I believe but not 100% sure.

**Comment by themadseventeen** [comment]
I am having the exact same issue.

Device: Oneplus 8
Android version: 14 (LineageOS 21, 21-20240904-NIGHTLY-instantnoodle)
App version: v0.14.2 (25)
Jellyfin version: 10.9.2

Relevant settings in app:
mpv player is enabled
Hardware decoding: mediacodec-copy
Video output: gpu-next
Audio-output: opensles

I don't have any screenshots but it appears exactly like sunnyd24's post.
Appears around same time, around 17 minutes into playback.

**Comment by jarnedemeulemeester** [comment]
Closing this in favor of #686
