### ISSUE TITLE
how to setup dev enviroment for android TV version?

### ISSUE THREAD

**Issue by picarica** [jarnedemeulemeester/findroid#774]
i wonder how can i setup a a development enviroment for this app are there some specific instructions how you build this app? i would like to try it out and look around

**Comment by Jcuhfehl** [comment]
Git clone the repo and open in android studio.

**Comment by picarica** [comment]
got it, i just installed sdk and ./gradlew releaseBinar
```
export ANDROID_HOME=~/git/findroid/android-sdk/sdk/
./gradlew assembleReleas
```
