### ISSUE TITLE
support shaders for mpv for upscaling(Anime4k)

### ISSUE THREAD

**Issue by smarttommyau** [jarnedemeulemeester/findroid#779]
**Is your feature request related to a problem? Please describe.**
It is always great to have better quality video even on mobile, as mobile display are quite good and the processing power of mobile are strong nowadays. 

**Describe the solution you'd like**
Include shaders like Anime4k on mpv player.

**Comment by Jcuhfehl** [comment]
I'm not knowledgable on the uses of shaders in mpv. But please, for the love of god, do *not* use anime4k. It's a sharpening filter and will simply cause ringing and wipe all details from your video.

If you want higher quality playback on higher resolution screens, you want to use a high quality scaling kernel like `ewa_lanczos`, which I've made an option for in #652. The only higher quality option *might* be some waifu2x model, but that doesn't run in realtime on desktop, let alone phones.

**Comment by jarnedemeulemeester** [comment]
While processing power of mobile devices is pretty good nowadays. Running shaders like Anime4k is very intensive, I'm not sure if even high end phones would be able to keep up.

Also the battery drain would be immense.

So no, I don't plan on including shaders like Anime4k
