### ISSUE TITLE
Broken endpoints for liking and marking as watched (possibly more)

### ISSUE THREAD

**Issue by prochy-exe** [jarnedemeulemeester/findroid#781]
**Describe the bug**
Can't mark items as liked or watched

**To Reproduce**
1. Go to any show, movie episode
2. Click on the like or watched icon

**Expected behavior**
Mark the item as liked or watched

**Device info (please complete the following information):**
 - Device: Google Pixel 7
 - Android version: 14
 - App version: latest debug version
 - Jellyfin version: 10.9.6

**Additional context**
I am running my server through an nginx proxy, the official app works fine, both through the proxy and directly, however findroid doesn't. I took notice that while the official app is making a request to:
```
/Users/userId/FavoriteItems/entityId
```
findroid is making a request to here:
```
/UserFavoriteItems/entityId?userId=userId
```
I did some testing manually using curl and i found out that the endpoint being used is actually not working at all, it returns a 403 despite the undocumented endpoint returning 200. 

**Screenshots**
![200](https://github.com/jarnedemeulemeester/findroid/assets/38187580/b489bd78-91b5-4c62-9c01-8bc0a2f6663c)
request in format /Users/userId/FavoriteItems/entityId
![403](https://github.com/jarnedemeulemeester/findroid/assets/38187580/abb0baeb-de98-4eeb-a59f-d202841917a1)
request in format /UserFavoriteItems/entityId?userId=userId

~TL;DR jellyfin probably broke their API and some endpoints do not work, I don't know the scope of this problem but other endpoints might be affected as well. I didn't see anything else personally however.~

~P.S I am using a base URL~
EDIT: I tried using the latest release version from google play and it works fine on it, its using the endpoint i mentioned before, the one that works

**Comment by prochy-exe** [comment]
Digging more into this showed up that the SDK uses those endpoints for example [here](https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/9b649586cdba40748b380e3ea7a6881e02df0fed/jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/PlayStateApi.kt#L42)

**Comment by jarnedemeulemeester** [comment]
Thanks a lot for the detailed report!

The cause of the issue was the arguments of those endpoints in the SDK switched places with the new 1.5.x version. 
I did have to switch a lot of arguments but apparently I forgot those.

Should be fixed now :smile:
