### ISSUE TITLE
Posters and thumbnails disappeared

### ISSUE THREAD

**Issue by zasfan** [jarnedemeulemeester/findroid#787]
When i open the app every poster is shown but the issue is that When i download some offline content and get in the offline mod they are still shown, after an hour they disappear 

**To Reproduce**
1. Open app
2. Download offline content
3. Get in the offline mod
4. After some time all posters and thumbnails disappeared

**Expected behavior**
When i use offline mod ı want show all thumbnails and posters

**Device info (please complete the following information):**
 - Device: xiomi mi 10t
 - Android version: 12
 - App version: Google play updated
 - Jellyfin version: 10.9.7

**Comment by Rdkang** [comment]
A similar issue to #525 and a fix is upcoming with #738 :) 🥳

**Comment by jarnedemeulemeester** [comment]
Duplicate of #525
