### ISSUE TITLE
Trying to play a video will trigger an ip ban by crowdsec

### ISSUE THREAD

**Issue by Tresillo2017** [jarnedemeulemeester/findroid#790]
**Describe the bug**
If you have crowdsec setup on your server and you try to play a video using findroid your ip will get banned due to `crowdsecurity/http-probing`

**To Reproduce**
1. Go to 'findroid'
2. Click on 'any video'

**Expected behavior**
Being able to playback a video without getting banned

**Device info (please complete the following information):**
 - Device: Samsung S21 FE
 - Android version: 14
 - App version: 0.14.2 (25)
 - Jellyfin version: 10.9.7

> Crowdsec is setup by reading the logs from swag and not from the jellyfin docker container

**Comment by jarnedemeulemeester** [comment]
Can you try with Intro Skipper disabled in the Player settings?
If you don't have the Intro Skipper plugin installed on the server it will cause a lot of 404 responses which will trigger the ban I think.

**Comment by Tresillo2017** [comment]
That was the issue, thanks a lot
