### ISSUE TITLE
Occasional crashes when pressing back button

### ISSUE THREAD

**Issue by Jcuhfehl** [jarnedemeulemeester/findroid#795]
Occasionally (~20% of the time I'd guess), the app crashes when pressing the back button from the player.
This certainly happens on mpv; I've not tested exoplayer.
It happens both on downloaded playback and streaming.

**Comment by jarnedemeulemeester** [comment]
It's definitely related to mpv.

Pushed a potential fix in 2af5c792efe2cf49c7d80df2cee94c15b5fa293e
But I'm not sure if it completely fixes the problem.
