### ISSUE TITLE
Make future versions 64 bits instead of 32

### ISSUE THREAD

**Issue by Ineocla** [jarnedemeulemeester/findroid#796]
**Is your feature request related to a problem? Please describe.**
With [32 bit apps soon becoming obsolete](https://arstechnica.com/gadgets/2022/10/the-pixel-7-tests-out-64-bit-only-android-cant-run-32-bit-apps/) it doesn't make much sense for findroid to still be a 32 bit app. Especially since it seems the app aims to support fairly modern devices

**Describe the solution you'd like**
Make the future findroid builds 64 bit

**Describe alternatives you've considered**
Keeping the app 32 bit doesn't make much sense unless the maintainers really insist on keeping compatibility with older models

**Additional context**
I stumbled upon this issue when i tried using findroid on my pixel 6a running grapheneos. Everytime i launch the app or start watching a movie or a show a warning message pops saying the app is 32 bit only and that grapheneos will soon drop support for 32 bit apps. I am running the latest findroid version (v0.14.12) from fdroid.

![Screenshot_20240725-143836](https://github.com/user-attachments/assets/a90322db-46f9-4741-b5f3-4e4040023d8b)

**Comment by Jcuhfehl** [comment]
Didn't you install the wrong version? There are also 64 bit releases on the releases page

**Comment by Ineocla** [comment]
> Didn't you install the wrong version? There are also 64 bit releases on the releases page

I installed the only availble version on izzyondroid
![Screenshot_20240725-153735](https://github.com/user-attachments/assets/f69db085-3a7b-4eda-9298-581e864326cd)
(For context i use neostore as my fdroid frontend)

**Comment by Jcuhfehl** [comment]
The one on izzyondroid is the 32 bit version. There already is a 64 bit version

**Comment by jarnedemeulemeester** [comment]
I may ask IzzySoft (maintainer of IzzyOnDroid) to switch out the armv7 (32-bit) build for the armv8 (64-bit) one. 

However for now if you want to easily download Findroid without using the Google Play store I recommend [Obtanium](https://obtainium.imranr.dev/).
Just add Findroid via it's GitHub URL (or search)

**Comment by lbrunkho** [comment]
@obfusk, it looks like you were the one to set up the Izzyondroid repo? This app only ships with a 32-bit apk there. Do you think we could get the 64-bit apk from the github releases there as well?

**Comment by obfusk** [comment]
IzzyOnDroid can only provide one APK per version. But developers can ask us to switch to 64-bit if that's preferred.

I'm responsible for our Reproducible Builds tooling; for changes to the repo itself, you'll want to ask @IzzySoft :)

**Comment by IzzySoft** [comment]
@jarnedemeulemeester I fully agree, you may ask :zany_face: So do you want to ask (as you did not include the `@` sign and I got no ping)? Findroid's 32bit version is already beyond the per-app size limit at IoD (limit: 30 MB, APK: 33.8 MB), the 64bit one is even a little bigger (35.8 MB). So I'd ask you in return to keep an eye on APK size :wink: 

Things to keep in mind: with very few exceptions (I know of only a single device), all 64bit devices do support 32bit APKs. But not a single 32bit device (yes, there are still some in use – and IzzyOnDroid wants to support "longevity" of devices, to avoid e-waste wherever possible) can support 64bit APKs. So switching to 64bit will drop support for some.

**Comment by lbrunkho** [comment]
@IzzySoft just a heads up, GrapheneOS has disabled 32-bit apps at the kernel level. I know this is a corner case, just something to keep in mind.

**Comment by IzzySoft** [comment]
@lbrunkho GOS has the "always latest from Google" approach. IoD has the "keep your devices useful and long-living" approach. A matter of choice, still: if you want to go with GOS, there's always Obtainium. Or GOS' own store, Accrescent. There are some security arguments for 64bit, but GOS going 64bit only is no argument for IoD to drop support for 32bit, sorry – and it also just affects a few devices (including the single 64bit-only device known to me).

**Comment by IzzySoft** [comment]
@jarnedemeulemeester as that issue [popped up at our end](https://gitlab.com/IzzyOnDroid/repo/-/issues/964) again, may I ask you once more for how to proceed with this? We can switch to the arm64 build, but the size is an issue here. Let me quote from my reply over there (I assume, GitLab didn't notify you about the mention – it constantly fails to send me notifications as well for more than a month now):

> A possible approach for that would be to enable "legacy compression" for the native libraries, which (rough ETA) would bring the size down by about 10 MB, and thus back into the per-app size limit here. To be transparent about it: enabling legacy compression would mean the libraries need to be extracted on-device on install (as they can no longer be used directly from within the APK then) – but other downsides are not known.

Would that be an option for you?

**Comment by jarnedemeulemeester** [comment]
@IzzySoft I indeed did not get a notification from GitLab.
But let's discuss it over there.

**Comment by IzzySoft** [comment]
Same. GitLab notification fail for me again – second time this year already. And since they've dropped their support for non-paying customers (their support@ mail just gives auto-replies, pointing to a web page sending you in circles through their site, just to finally return where you started), I have no clue how to fix that). So, another notification here 🙈
