### ISSUE TITLE
Can't download a file large file

### ISSUE THREAD

**Issue by rodude123** [jarnedemeulemeester/findroid#799]
**Describe the bug**
Download fails for large file. I'm not too sure if it's time or size. 

**To Reproduce**
1. Open an episode of a show (How I met your mother Season 1 Episode 1 - Pilot)
2. Click on download

**Expected behavior**
The file should be downloaded.

**Screenshots**
![Screenshot_20240730-173211536 (1).jpg](https://github.com/user-attachments/assets/494e117b-5e06-486c-82ed-5f87b906aedf)
![Screenshot_20240730-173340838.jpg](https://github.com/user-attachments/assets/e749a8f7-f9b1-4cd5-80d9-a8b3cc3e847b)

**Device info (please complete the following information):**
 - Device: [ROG Phone 5]
 - Android version: [12]
 - App version: [v0.14.2 (25)]
 - Jellyfin version: [10.9.7]

**Additional context**
I'm not too sure what I'm doing wrong. I'm just downloading a 393MB file
I can provide more info if required and asked for.

**Comment by NineBallo** [comment]
I'm having the same issue. Weirder is multiple files cause it to fail faster, and usually around 4-5 will kill the entire queue. 

In my case I'm running android 14 but am also able to download short/smaller videos.

**Comment by Jcuhfehl** [comment]
As far as I know, this is because the android download manager (which is used by findroid) doesn't attempt to resume a download if fails for a bit. So if you lose your wifi connection for a couple of seconds while downloading, the download could very well fail completely.
This problem is made worse by slower wifi, larger files, and downloading multiple files at once, all because the total time to download increases, so there is a larger chance of a temporary disconnect.

**Comment by NineBallo** [comment]
> As far as I know, this is because the android download manager (which is used by findroid) doesn't attempt to resume a download if fails for a bit. So if you lose your wifi connection for a couple of seconds while downloading, the download could very well fail completely.
> This problem is made worse by slower wifi, larger files, and downloading multiple files at once, all because the total time to download increases, so there is a larger chance of a temporary disconnect.

So this does seem to be part of it as viewing the logs (logcat) points in this direction. However, when connected with ethernet, the same issue exists... which doesn't make sense for this kind of issue. 

Viewing the logs of download manager, I'm getting a lot of warnings for: 

"...Job didn't exist in Jobstore..."
"...onNetworkChanged() not implemented in com.android.providers.downloads.DownloadJobService. Must override in a subclass."


And one error:
"...NotificationService: package enqueue rate is **x**. Shedding 0|com.android.providers.downloads..."

**Comment by NineBallo** [comment]
Alright, I'm not sure why but I factory reset my device and it works now :/. Just gonna run with it but I guess its not an issue with this program. I am however very confused by what could've caused it...

**Comment by jarnedemeulemeester** [comment]
Most likely an issue with the Android Download Manager and not with Findroid. When a connection is interrupted the download will fail, the chance of this happening with larger files is obviously higher.
