### ISSUE TITLE
Setting volume & brightness on screen

### ISSUE THREAD

**Issue by gauth-fr** [jarnedemeulemeester/findroid#8]
It would be great to be able to set the volume & brightness by "sliding" up or down on the screen.
Like the official app in fact, its a very useful features.

Thanks!

**Comment by jarnedemeulemeester** [comment]
Yes would be useful I agree. 

I will look at this one later when I'm finished with some more important issues :)

**Comment by jarnedemeulemeester** [comment]
This has been implemented for some time now, I forgot to close this :smile:
