### ISSUE TITLE
Trickplay Not Working for Jellyfin 10.9.x

### ISSUE THREAD

**Issue by KeshavKhanth** [jarnedemeulemeester/findroid#801]
**Describe the bug**
After 10.9.x upgrade Jellyfin natively support trickplay instead of jellyscrub.
And it generate .jpg collab img of media in the interval of every 10sec. Before that .bmp format was used by jellyscrub.
After I upgraded 10.9.x it did recommended to convert .bmp to .jpg img and delete old .bmp files to save storage. 
And In web it working fine. But Not in Findroid. 

**Device info (please complete the following information):**
 - Device: [Nothing 2a]
 - Android version: [14]
 - App version: [e.g. v0.1.1 (2)]
 - Jellyfin version: [e.g. 10.9.7]

**Comment by Natanel-Shitrit** [comment]
Jellyfin native trickplay support has been added but yet to be released.

It will be available in the next Findroid release.

**Comment by Natanel-Shitrit** [comment]
Released in `v0.15.0`!

**Comment by KeshavKhanth** [comment]
> Released in `v0.15.0`!

Thanks @Natanel-Shitrit . Btw when can we expect the Android TV release.
