### ISSUE TITLE
Preferred language does not select proper language on MPV, #737 cont. 

### ISSUE THREAD

**Issue by nattadasu** [jarnedemeulemeester/findroid#804]
**Describe the bug**
This is a follow-up issue of #737, which may also caused by https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/common/src/main/java/androidx/media3/common/util/Util.java#L3837.

Although that it does correctly detect language codes, when a video contains `msa` (Malaysian) subtitles and preferred language is `ind`, MPV rather pick `msa` subtitle instead.

When Malay subtitle does not exist, MPV set to default embedded subtitle instead, or in some rare cases, none selected.

**To Reproduce**
0. Obtain subtitles in English and Indonesia
1. Set preferred subtitle language to `Indonesia`
2. Observe selection
3. Fetch Malaysian subtitle on same media.
4. Play and observe selection

**Expected behavior**
Findroid should pick Indonesian even if Malaysian subtitle exist.

**Screenshots**

*see comments*

**Device info (please complete the following information):**
 - Device: Xiaomi Redmi 9T
 - Android version: 12 (MIUI 14.0.2 Stable)
 - App version: 0.15.0 (26), Libre/GitHub release
 - Jellyfin version: 10.9.8

**Additional context**
Using mpv with `mediacodec-copy` and `gpu` option

**Comment by nattadasu** [comment]
Following is steps to replicate the issue, forgot to attach it:
https://github.com/user-attachments/assets/359df425-424d-4c6c-9d14-c4dd36c52160

**Comment by nattadasu** [comment]
**Update:** Findroid will not select Indonesian if default video subtitle is English and does not have Malay subtitle

https://github.com/user-attachments/assets/e40c3d5d-ffc0-4036-be92-6980078e2d8d

It seems that there's weird issue between Findroid and the player when communicating which subtitle to select, and prioritized Malaysian instead

**Comment by jarnedemeulemeester** [comment]
Added the same fix before passing the language code to mpv as done for the selection dialog.
mpv should now correctly select Indonesia
