### ISSUE TITLE
Subtitles won't display after seeking with tricklay and subtitles track is changed

### ISSUE THREAD

**Issue by enter-a-random-username** [jarnedemeulemeester/findroid#806]
**Describe the bug**
Subtitles won't show

**To Reproduce**
1. Use seeking with trickplay enabled
2. Change/enable subtitle track
3. Subtitles are gone/won't show

**Expected behavior**
Show subtitles

**Device info (please complete the following information):**
 - App version: 0.15.0

**Additional context**
- Disabling trickplay on seeking will avoid the issue

**Comment by jarnedemeulemeester** [comment]
I'm unable to reproduce this. 
Do you mean seeking by dragging on the timebar or the gesture?
In both instances the subtitles seem to continue to work fine.

Are you expiriencing this issue with the default player or mpv?

**Comment by JorgeLNJunior** [comment]
I have the same issue, but only with PGS subtitles. The subtitles disappear when I change the default one, drag the time bar, or double-tap the left or right side of the screen. Playing an episode with tracked progress does not show subtitles either, both in the default player and in MPV.

Jellyfin: 10.9.9
Findroid: 0.15.1
