### ISSUE TITLE
When i download a video and use mpv the app crashes. If i reproduce in Stream the video play fine, bur when downloader It the app crashes

### ISSUE THREAD

**Issue by davidborlas** [jarnedemeulemeester/findroid#810]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device info (please complete the following information):**
 - Device: [e.g. Google Pixel 3]
 - Android version: [e.g. 12]
 - App version: [e.g. v0.1.1 (2)]
 - Jellyfin version: [e.g. 10.8.5]

**Additional context**

**Comment by Jcuhfehl** [comment]
Duplicate of #805
