### ISSUE TITLE
Slight inconsistencies with the latest version (0.3.1)

### ISSUE THREAD

**Issue by roand0617** [jarnedemeulemeester/findroid#83]
Hello, I would like to share my experience with the latest version of Findroid (0.3.1)

- The images of the episodes are not seen in the Downloads section.
- When downloading any content starts, if it is cancelled, it still appears in the download section.
- When you play something and you go to the phone screen and come back, the content doesn't continue, the app opens again.
- When I select audio or subtitles while playing something, the android navigation bar appears and does not hide again, leaving the subtitles button behind.

If more information is required for the reproduction of any of these, I will gladly help.

Thank you very much for the good work.

**Comment by jarnedemeulemeester** [comment]
Most of these issues I already know about but thanks for creating an issue.
I will keep this open untill they are all fixed.

Just wanted to let you know that I'm not dead and plan on fixing these eventually :)
