### ISSUE TITLE
Autoplay next isn't working

### ISSUE THREAD

**Issue by UriSheinman** [jarnedemeulemeester/findroid#837]
**Describe the bug**
Whether it's from the skip credits button or waiting for an episode to end, the episode will be paused and not auto play. However when clicking the next episode button it does autoplay.

**To Reproduce**
1. Go to any episode in a show
2. wait for episode to end or skip credits.
3. See error

**Expected behavior**
Episodes should play automatically as they are reached to.

**Screen Cap**

https://github.com/user-attachments/assets/7d99da91-ed2b-46a9-b7e7-7f3b55704114

**Device info (please complete the following information):**
 - Device: Nothing Phone (1)
 - Android version: 14
 - App version: 0.15.2
 - Jellyfin version: 10.9.11

**Comment by Vinay-Khanagavi** [comment]
Hi! I'd like to work on this issue. I'll look into the auto play and skip credits functionality to resolve the problem. Thanks!

**Comment by jarnedemeulemeester** [comment]
> @jarnedemeulemeester would love to see a bugfix release including this. Keeping screen on and paused with player UI isn't that nice towards OLED

I'll release a new version soon. Just trying to get one more fix in
