### ISSUE TITLE
Save playback position in offline mode

### ISSUE THREAD

**Issue by Theta-Dev** [jarnedemeulemeester/findroid#86]
When I use findroid in offline mode and stop the playback, it does not remember the playback position and jumps back to the last playback position stored in online mode.

Findroid should keep track of the playback positions when it is not connected to the server and ideally sync them back when reconnecting.

**Comment by Jcuhfehl** [comment]
Findroid already does this, so I think this issue should be closed.

**Comment by jarnedemeulemeester** [comment]
This has indeed been fixed for some time now
