### ISSUE TITLE
Support for older SDKs (like v24) for older TVs?

### ISSUE THREAD

**Issue by thcrt** [jarnedemeulemeester/findroid#866]
I have an Android TV that's a little bit older but still works perfectly well. I'd love to install Findroid on it, especially given that the official Jellyfin app doesn't work at all on it. This would require support for older SDK versions, namely 24 in my case. Since a lot of TVs only have limited software updates, support for older SDKs would greatly improve TV support.

I'm not experienced with development for Android/Android TV, so this might be much more work than it seems. Obviously, I'd understand if that were the case.

Cheers!

**Comment by jarnedemeulemeester** [comment]
At the moment there are no plans to lower the min SDK. 
I do understand that most TVs run older software and rarely get updates. 

The TV version will be initially released with the current min SDK of 28. Once it is stable I may look into lowering the min SDK.

**Comment by thcrt** [comment]
That makes sense, I totally understand.

Thanks for your work on Findroid :)
