### ISSUE TITLE
Unknown error for login with Jellyfin 10.10.0

### ISSUE THREAD

**Issue by AkashRajpurohit** [jarnedemeulemeester/findroid#877]
### Describe your issue

After upgrading Jellyfin to 10.10.0, findroid fails to login with "Unknown error".
Confirmed that this is affected from 10.10.0 since the previous stable version 10.9.11 works fine.

### Steps to reproduce

1. Setup Jellyfin server on 10.10.0.
2. Try logging in via findroid app.

### Expected behavior

Login should be successful.

### Player

default (ExoPlayer)

### Device

Moto Edge

### Android version

14

### App version

0.15.3 (29)

### Jellyfin version

10.10.0

**Comment by lucastucious** [comment]
Same issue

**Comment by formeo14** [comment]
Sad that this issue was issued half a year ago and no one gave it a deeper look. 
It now happens on all Findroid apps connected to my server. Version 10.10.0

**Comment by jarnedemeulemeester** [comment]
This is an upstream issue with the Jellyfin server. I have submitted a bug report.
https://github.com/jellyfin/jellyfin/issues/12948

I believe a temporary workaround is to restart the Jellyfin server. After the restart a single login attempt should work

**Comment by AkashRajpurohit** [comment]
What I did as a workaround for now was downgrade to 10.9.11 -> Login on findroid app -> upgrade server to latest version.

Logout and login again might fail but hoping that the upstream issue will get resolved till then.

Thanks for looking into this @jarnedemeulemeester

**Comment by jarnedemeulemeester** [comment]
This is fixed from Jellyfin version 10.10.2 and onwards
