### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [jarnedemeulemeester/findroid#88]
Please consider releasing Findroid on F-Droid.

**Comment by jarnedemeulemeester** [comment]
Yes! I will look into that for the next release.
Probably 0.4.0.

**Comment by thebiblelover7** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 It is currently on IzzyonDroid's F-droid repo

**Comment by Dperrigo18** [comment]
Thanks for the interest and putting it on IzzyonDroid! This app is really cool.

**Comment by jarnedemeulemeester** [comment]
Since all requirements are met now (from what I can tell), I will start looking into publishing on F-Droid
