### ISSUE TITLE
Add custom branding to findroid

### ISSUE THREAD

**Issue by UriSheinman** [jarnedemeulemeester/findroid#882]
**Describe the solution you'd like**
I have custom branding for jellyin, custom title logo and such. I think having a setting that adapts the apps name from findroid to the server name, and for findroid to draw the app's logo from the server and add the custom title next to home, image attached.
![Screenshot_20241117-123556.png](https://github.com/user-attachments/assets/30b03ab2-7faa-40c4-9f16-18cb70ef0553)

![Screenshot_20241117-123620.png](https://github.com/user-attachments/assets/02ffc7f0-b989-4f1a-984d-7cbc032ec62c)

**Describe alternatives you've considered**
Recompiling the app with the different logo and title built in, but that's cumbersome and needs to be done for every update.

**Comment by jarnedemeulemeester** [comment]
Sorry this is not something I will be supporting.
There is no API in Jellyfin to retrieve the branding / a custom logo.

The compose rewrite (which I am working on) will probably get rid of the "Home" title anyway and replace it for a full width search bar.
