### ISSUE TITLE
Browsing library is broken in landscape mode

### ISSUE THREAD

**Issue by Ge082** [jarnedemeulemeester/findroid#89]
**Describe the bug**
Portrait mode does display stuffs as expected but landscape mode display very huge posters
Home page is displayed correctly though

**To Reproduce**
Go to any library
Go to landscape mode

![Screenshot_20220213-021321_Findroid](https://user-images.githubusercontent.com/76789478/153734209-5e99af0d-7b5d-4bab-9172-d39bf6c9ffac.jpg)
![Screenshot_20220213-021332_Findroid](https://user-images.githubusercontent.com/76789478/153734212-0affcfc2-e913-4b0a-b3d1-73fc0be57cd3.jpg)

** Possibly a feature request with that **
Add an option in settings to let user customize how many items to display on both portrait and landscape mode per rows, 2 is good but when browsing a large library it's clumsy

**Comment by jarnedemeulemeester** [comment]
Yes in the future I will add an option in the settings to change the amount of columns.
Same for landscape mode.

**Comment by Oniicode** [comment]
An option to reduce those huge margins between the columns would be nice too.
