### ISSUE TITLE
Offline Playback Fails After Downloading Latest Version

### ISSUE THREAD

**Issue by wintsa123** [jarnedemeulemeester/findroid#897]
### Describe your issue

After downloading the latest version for offline use, it fails to play offline. When I turn off the network, an error occurs. I believe that the metadata should be downloaded and stored at the same time when the offline download is done.

### Steps to reproduce

Steps to Reproduce:

Download the latest version of the app for offline use.
Turn off the network connection.
Attempt to play the downloaded content offline.
An error message appears, and the content fails to play.
Expected Behavior:
The content should play offline without any errors, and metadata should be downloaded and stored alongside the content during the offline download process.

### Expected behavior

offline playback！

### Screenshots

![Screenshot_2024-11-29-20-23-03-49_aff99014c254344a005aaf8c1683039d](https://github.com/user-attachments/assets/4e09c001-93ff-4a5f-83b7-569f9af24473)
![Screenshot_2024-11-29-20-22-13-96_aff99014c254344a005aaf8c1683039d](https://github.com/user-attachments/assets/cbcfcff2-e621-4774-b3e7-a289cc141c82)

![Screenshot_2024-11-29-20-22-11-74_aff99014c254344a005aaf8c1683039d](https://github.com/user-attachments/assets/8ef343eb-058f-43b7-8587-67512dd4518e)

### Device

realme gt7pro

### Android version

15

### App version

v0.15.3

### Jellyfin version

10.9.11

**Comment by RyanFoulds** [comment]
Does the following resolve the playback issue?
1. Download content
2. Disable network connection
3. Turn on offline mode in Findroid settings
4. Attempt playback

There is meant to be a SnackBar that invites you to switch to offline mode when connection fails from the downloads screen. For some reason that doesn't appear on my phone (Pixel 6a) but I'm unable to reproduce on a virtualized environment. 

#627 might also address this.

At least this might provide a workaround for the time being.

**Comment by wintsa123** [comment]
> 以下是否解决了播放问题？
> 
> 1. 下载内容
> 2. 禁用网络连接
> 3. 在 Findroid 设置中打开离线模式
> 4. 尝试播放
> 
> 有一个 SnackBar，当连接失败时，它会邀请您从下载屏幕切换到离线模式。~由于某种原因，它没有出现在我的手机 （Pixel 6a） 上，但我无法在虚拟化环境中重现。~编辑：SnackBar **确实**会在连接失败时显示，但连接失败所需的时间会有所不同，具体取决于故障模式。如果您连接到另一个网络（即不是您的 JellyFin 服务器实例的网络），则超时需要更长的时间，如果您在提示出现之前单击下载的节目，它将不会出现在特定于节目的下载页面上，只会出现在顶级下载页面上。解决方案是在主下载页面上等待几秒钟，直到您被邀请启用离线模式。
> 
> #627 也可能通过自动切换到离线模式来解决此问题。

nice try!
