### ISSUE TITLE
UI Change - Better experience

### ISSUE THREAD

**Issue by kvnjonathan70** [jarnedemeulemeester/findroid#911]
Hi, i made some UI adjustments with your app for better user experience. If you like it or found useful then would you mind implementing it ?

1. Changed Player_Background to Transparent
2. Realinged and reduced size of exo player icons
3. Removed item_banner, now it looks clean without it ( the crop always provided cut image) 
4.  on large screen,on mpv player, CC text is way to large, is there any way to control it? i cant find it's location

![Screenshot_20241219-131817](https://github.com/user-attachments/assets/bd5b2a6e-e1e7-42b3-850b-7784b6a4fb40)
![Screenshot_20241219-131841](https://github.com/user-attachments/assets/ce59bd86-9a7a-4257-8ca6-383534e2f7a3)
![Screenshot_20241219-131910](https://github.com/user-attachments/assets/83908ef4-8852-4d9e-bf3c-303780c5a58c)
![Screenshot_20241219-132011](https://github.com/user-attachments/assets/20eb29bb-7716-46bc-91ec-e934a23e771e)

**Comment by jarnedemeulemeester** [comment]
Thank you for the feedback. However some of the changes look strange to me.

1. The reason the player background is not 100% transparant is to add contrast to the text and button. Imagine the video displaying a completely white frame. The controls and text would not be visible.
2. The placement of the buttons could maybe be improved a bit. This is something I will take a look at in the future.
3. Removing the item_banner makes the movie page feel really empty and lifeless. I do think we need an alternative layout for landscape view on mobile tho.
4. mpv is configured using config files located in the internal app storage. I don't remember the excact location but you can edit them if you want to. In the future you will be able to edit these directly inside the settings of the app.

At the end of the day everyone has different preferences.
