### ISSUE TITLE
I want to know how to enable auto-play when switching to the next episode of a TV series. 

### ISSUE THREAD

**Issue by Insua** [jarnedemeulemeester/findroid#918]
Currently, after one episode finishes playing on my app, it loads the next episode, but I have to manually click the play button to start the next episode. How can I configure it to auto-play?

**Comment by jarnedemeulemeester** [comment]
Are you using mpv player? If so there is a bug in the current released version which prevents it from auto playing.
This has been fixed and will be in the next release.

**Comment by Insua** [comment]
yep,wish the next release
