### ISSUE TITLE
[Feature request] More metadata

### ISSUE THREAD

**Issue by BluePixel4k** [jarnedemeulemeester/findroid#93]
More metadata like Video resolution, audio track and subtitles.
Excample picture is from the original jellyfin app.

Fittingly, a drop down menu for the audio track would be handy (if more than one is available).

<img src="https://user-images.githubusercontent.com/77979781/154714849-103756f7-2b81-4c5c-8ecb-0ca2019db022.png" width="300" />

**Comment by Yash-Garg** [comment]
@jarnedemeulemeester I would like to try and work on this, can you assign it to me? Thanks!

Great work on the app btw :)

**Comment by Yash-Garg** [comment]
Hey @jarnedemeulemeesterm, does this look fine to you? Too much subtitles cause too many lines, we can maybe ellipse it?

<p align="center">
  <img width="40%" src="https://user-images.githubusercontent.com/33605526/215040800-b0cbcbbb-db8a-47d2-9aa0-c9a3ba5f2280.png">
  <img width="40%" src="https://user-images.githubusercontent.com/33605526/215040816-94f7b416-3f69-48c8-b560-2889e0fc2420.png">
  <img width="40%" src="https://user-images.githubusercontent.com/33605526/215040834-aac23e49-956c-4a46-8d41-bfa0df628185.png">
</p>

**Comment by jarnedemeulemeester** [comment]
Looks pretty good. I would indeed set it to a maximum of 3 lines. 
Also do you think we should move it underneath the writers, just like the official app?  With maybe a little bit of spacing between them.

**Comment by Yash-Garg** [comment]
> @Yash-Garg Looks pretty good. I would indeed set it to a maximum of 3 lines. Also do you think we should move it underneath the writers, just like the official app? With maybe a little bit of spacing between them.

Sure, will make the changes and post screenshots for the same. 

Although the official app has it on top now, I think they changed it later on? Should I keep it as it is then or move it below the writers @jarnedemeulemeester?

<img width="70%" src="https://user-images.githubusercontent.com/33605526/215270456-132d3752-6c24-41dd-b193-dfa12a9fcea2.png">

**Comment by jarnedemeulemeester** [comment]
@Yash-Garg You can keep them on top.

> We can also keep it like the current official application, like below:

Looks good like that!

**Comment by Yash-Garg** [comment]
> @Yash-Garg You can keep them on top.
> 
> > We can also keep it like the current official application, like below:
> 
> Looks good like that!

Great, so I'll keep it like the current official app.
