### ISSUE TITLE
About subtitles

### ISSUE THREAD

**Issue by Amazingzz614** [jarnedemeulemeester/findroid#98]
It cannot load the Subtitle file
Screenshots:
1.Findroid
![Findroid](https://user-images.githubusercontent.com/61904643/154965142-c92809b1-2844-49fc-9513-c819a441d51f.jpg)
2.Jellyfin
![Jellyfin](https://user-images.githubusercontent.com/61904643/154965156-23cda72b-447d-4b6a-b121-f25af9c77fd3.jpg)

Device info:
 - Android version:11
 - App version:0.3.2

**Comment by Summon528** [comment]
If you are talking about external subtitle, then it is not supported #7

**Comment by jarnedemeulemeester** [comment]
I'm going to assume these are external subtitles and close this issue, if not please reopen.

Support for external subtitles is tracked in #7
