### ISSUE TITLE
[Feature request] Music Videos support

### ISSUE THREAD

**Issue by asgardius** [jarnedemeulemeester/findroid#99]
I have a music video library on my Jellyfin server, can see these videos listed on Findroid, but currently i cannot play them

**Comment by jarnedemeulemeester** [comment]
Music video libraries are currently not in the scope of the project

**Comment by voronind-com** [comment]
@jarnedemeulemeester why? You do understand that "music videos" is actually a broad term? There's no way to watch Youtube or other non-movie media. I understand that there's a finamp for music, but "music videos" is not only about music. Thanks!
